fix(List): Added aria roles for list/list-item
Semantic-Org/Semantic-UI-React pull request #1001
Opened 2016-12-07 19:52 UTC by fracmak

List elements are missing the appropriate roles to indicate what is being displayed.

Documentation: https://www.w3.org/TR/wai-aria/roles#list

2016-12-08 05:44 UTC, levithomason requested changes
Just one comment regarding organizing tests.  Looks great otherwise 👍

2016-12-08 05:44 UTC, levithomason commented on test/specs/elements/List/List-test.js
> +      wrapper.should.have.prop('role', 'list')
Would prefer we add separate `it()` blocks for the accessibility assertions:

```jsx
it('is accessible', () => {...})
// or 
it('has proper aria props', () => {...})
```

Something to this effect.  The idea is to keep the `it()` strings descriptive to exactly what is being asserted inside of them.

2016-12-08 05:51 UTC, levithomason commented
The test organization used in https://github.com/Semantic-Org/Semantic-UI-React/pull/1006 is exactly what I was thinking.  Let's do that here as well.

2016-12-08 05:59 UTC, fracmak commented
tests reorganized

2016-12-09 01:35 UTC, levithomason commented
Made a trivial fix here, mostly to debug why CI is suddenly not running at all... Hm.

2016-12-09 01:39 UTC, levithomason commented
So odd, gonna have to double back and test these manually.

2016-12-10 00:02 UTC, merged

2016-12-10 17:18 UTC, levithomason commented
Releasing now as `semantic-ui-react@0.62.1`.