fix(Icon): added aria-hidden attribute to icon
Semantic-Org/Semantic-UI-React pull request #1002
Opened 2016-12-07 19:58 UTC by fracmak

Icons are primary for decoration or visual style and should be hidden from screen readers. Additional markup can be added to allow screen readers to read the icons if necessary, but by default all icons should be hidden.

Documentation: http://fontawesome.io/accessibility/

2016-12-08 05:53 UTC, levithomason requested changes

2016-12-08 05:53 UTC, levithomason commented on test/specs/elements/Icon/Icon-test.js
> +    wrapper.should.have.prop('aria-hidden', 'true')
Same comment here, let's pull these assertions into their own `it()` block.

2016-12-08 06:04 UTC, fracmak commented on test/specs/elements/Icon/Icon-test.js
> +    wrapper.should.have.prop('aria-hidden', 'true')
updated

2016-12-09 01:40 UTC, levithomason approved these changes

2016-12-09 01:40 UTC, levithomason commented
Again, will manually test and release this later.

2016-12-10 00:02 UTC, merged

2016-12-10 17:18 UTC, levithomason commented
Releasing now as `semantic-ui-react@0.62.1`.