Layout examples
Semantic-Org/Semantic-UI-React pull request #1039
Opened 2016-12-16 10:16 UTC by iamcaleberic

- Porting SUI layouts examples

2016-12-16 10:18 UTC, iamcaleberic commented
@levithomason Would like your thoughts on current implementation before i continue with the porting 
## issues
 - Routing 
 - Showing source for layout examples

2016-12-17 21:05 UTC, levithomason commented
Here's what I'm thinking.

### Structure

We put layout examples in `/docs/app/layouts` to keep them separate from the component examples.  Then, we make the routes dynamic by creating a Webpack context of this directory.

I'm thinking the layouts need to render as a full page view without the sidebar in order to be effective.  I'll need to rework some components to make this happen.

### Showing source

Again, I think this needs to be done differently that in the current examples.  What if we showed a circular floating button in one of the corners of the every layout, when clicked, we could show the source.  Perhaps we would show source in a modal over the layout itself, or, we could toggle the entire page from the rendered view to the source editor and back.

I think the primary concern here is that the source will be very large so we'll likely need to take up the entire page, or at least most of it.

***

If you can move the layout to be in the directory structure proposed above, I'll come back to this PR and update it to handle the routes and showing source for layouts as soon as I can.

2016-12-19 10:54 UTC, iamcaleberic commented
- I agree on the layouts being full page view
- I think we can toggle between the view and the source editor for showing source

2016-12-19 18:09 UTC, levithomason commented
Great!  If you want to take a stab at any of that, please do.  Otherwise, I'll get to this as soon as I am able.

2017-01-24 01:24 UTC, levithomason requested changes

2017-01-24 01:24 UTC, levithomason commented on docs/app/Views/Layouts.js
> +  <Container as='div'>
Heads up, the default component class is `div` so we can remove all `as='div'` props since it is redundant.

2017-01-24 01:24 UTC, levithomason commented on docs/app/Views/Layouts.js
> +    <Segment masthead vertical>
There is no `masthead` prop, let's remove that.

2017-01-24 01:24 UTC, levithomason commented on docs/app/Views/Layouts.js
> +    <Container as='div' className='main intro'>
Let's also remove `className='main intro'`, we shouldn't have any extra classNames on the layouts as we have no additional styles to apply.  If the layouts require additional custom styling on top of the default theme, then we'll have to reconsider how we go about that.

2017-01-24 01:26 UTC, levithomason commented on docs/app/Views/Layouts.js
> +          <div className='sub header'>Examples of using Semantic UI React</div>
Here we can use `<Header.Subheader />` instead of `className`.

2017-01-24 01:37 UTC, levithomason commented
I'm adding route support for the view ATM, I'll address some of the other issues as well.

2017-01-24 02:27 UTC, levithomason commented
OK, I've stubbed out the routes and layout files themselves.  I also included a back button automatically for the layout views.  You should be good to simply update the layout files.  Let me know if you run into any issues 👍

2017-01-24 02:27 UTC, levithomason approved these changes

2017-01-24 07:07 UTC, iamcaleberic commented
@levithomason thanks alot

2017-01-24 19:22 UTC, levithomason commented
No problem, ping me when the other layouts are in and I'll make sure to get the full page source and editor going.

2017-04-20 11:22 UTC, iamcaleberic commented
@levithomason the file routes.js has changed quite significantly and I have alot of conflicts on it

2017-04-20 18:47 UTC, levithomason commented
Yep, I'll label this issue for assistance and @layershifter or myself will get to it soon.

2017-06-01 10:38 UTC, layershifter commented
I've updated to latest `master`, updated routes and performed some fixes. LGTM.
I will review existing layout examples.

2017-06-06 12:03 UTC, layershifter commented
I've updated the start comment with TODO, working on other examples.

2017-06-13 08:48 UTC, iamcaleberic commented
@layershifter thank you for fixing the issues. I updated the checklist I had four layout examples left and some styling for the existing ones.

2017-06-13 09:02 UTC, layershifter commented
@iamcaleberic Thanks for the follow up. I updated checklist again, I saw that we have some existing examples, however I mark only that I checked.

2017-06-13 14:27 UTC, iamcaleberic commented
@layershifter managed to get all the layouts up but without styling

2017-07-05 10:25 UTC, layershifter reviewed
Updated all examples, fixed styling and merge conflicts. @levithomason we're ready for initial review there

BTW, @iamcaleberic thanks for your work there!

2017-07-12 14:38 UTC, iamcaleberic commented
@layershifter thanks for the assist in completing this....

2017-07-18 03:21 UTC, merged

2017-07-18 03:22 UTC, levithomason commented
Thank you @iamcaleberic and @layershifter for pushing this one over the finish line!

2017-07-25 05:13 UTC, levithomason commented
Released in `semantic-ui-react@0.71.2`

2017-08-20 02:24 UTC, jackjwilliams commented
This is awesome! Thank you so much for this contribution, I've been looking for full blown layout examples. I was wondering, I noticed the "Home Page" example on regular SUI has a responsive hamburger menu, does SUI React not support this?

2018-01-11 19:14 UTC, snekse commented
Yeah, I think @jackjwilliams found a bug. 

https://semantic-ui.com/examples/homepage.html
vs.
https://react.semantic-ui.com/layouts/homepage