fix(Portal) portal should take focus when open and restore when closed
Semantic-Org/Semantic-UI-React pull request #1154
Opened 2017-01-13 06:14 UTC by fracmak

All portal based elements (modals, popups, etc) are not keyboard accessible because they're usually injected at the end of the dom and not in the flow of the document. This pull request fixes that by putting focus on the popup when open (except when closeOnTriggerBlur is true) and restores the focus to the last known focus point on close.

2017-01-16 16:59 UTC, levithomason requested changes

2017-01-16 16:59 UTC, levithomason commented on src/addons/Portal/Portal.js
> +      this.triggerNode = document.activeElement
Nit: Could we use another name here?

If a portal is triggered programmatically, the `activeElement` will not necessarily be the `triggerNode`.  These are only the same when the user clicked on a trigger, such as a button.  How about something like `previousActiveElement` or similar?

2017-01-16 16:59 UTC, levithomason commented on src/addons/Portal/Portal.js
> +      setTimeout(() => this.portal && this.portal.focus())
I'd like to pull this side effect out of the render method if at all possible.  I haven't the bandwidth at the moment to find a better place myself, but open to suggestions.

2017-01-17 03:10 UTC, fracmak commented on src/addons/Portal/Portal.js
> +      setTimeout(() => this.portal && this.portal.focus())
Technically this code is being called by either componentDidMount or componentDidUpdate depending on when 'open' is set to true which is after the render method. Or are you saying you'd like me to make a named helper function that's called here? There's no later life cycle function I can use to trigger this behavior

2017-01-17 14:25 UTC, fracmak commented on src/addons/Portal/Portal.js
> +      this.triggerNode = document.activeElement
done

2017-01-17 19:30 UTC, levithomason commented on src/addons/Portal/Portal.js
> +      setTimeout(() => this.portal && this.portal.focus())
Oh, I see, thanks for the clarification.  From my initial pass I assumed this was called in a `render()` method itself.  -1 for assumptions :)

2017-01-17 19:33 UTC, levithomason approved these changes

2017-01-17 19:33 UTC, merged

2017-01-17 20:12 UTC, levithomason commented
Released in `semantic-ui-react@0.64.1`.