style(Checkbox|Flag|Image|Radio): propTypes cleanups
Semantic-Org/Semantic-UI-React pull request #1155
Opened 2017-01-13 09:01 UTC by layershifter

This PR is part of work for removing propTypes in production bundle (#524, #731).

Affects following components:

- `Checkbox`
- `Flag`
- `Image`
- `Radio`

2017-01-13 09:56 UTC, layershifter commented on src/elements/Flag/Flag.js
> + **/
Added description :smile:

2017-01-13 09:57 UTC, layershifter commented on src/elements/Flag/Flag.js
> +  const classes = cx(name, 'flag', className)
`className` is last

2017-01-13 09:57 UTC, layershifter commented on src/addons/Radio/Radio.js
> +  /** Format to emphasize the current selection state. */
Dots :smile:

2017-01-13 09:57 UTC, layershifter commented on src/addons/Radio/index.d.ts
> +export const Radio: React.StatelessComponent<RadioProps>;
New typings for `Radio`.

2017-01-13 10:06 UTC, layershifter commented on test/specs/commonTests.js
> -    })
We don't have `_meta.props` now.

2017-01-13 10:07 UTC, layershifter commented on test/specs/commonTests.js
> -      })
^

2017-01-16 16:44 UTC, levithomason requested changes

2017-01-16 16:44 UTC, levithomason commented on src/addons/Radio/Radio.js
> +  /** Format to emphasize the current selection state. */
😄

2017-01-16 16:44 UTC, levithomason commented on src/elements/Flag/Flag.js
> + **/
The closing tag for a doc block only needs one asterisk:

```js
/**
 * ...
 */
```

2017-01-16 16:44 UTC, levithomason commented on test/specs/commonTests.js
> -    _.each(Component._meta.props.verticalAlign, (propVal) => {
Let's implement a similar solution as we will do in https://github.com/Semantic-Org/Semantic-UI-React/pull/1165#discussion_r96260999

2017-01-16 16:44 UTC, levithomason commented on test/specs/commonTests.js
> -      })
^

2017-01-17 09:26 UTC, layershifter commented on test/specs/commonTests.js
> -    _.each(Component._meta.props.verticalAlign, (propVal) => {
Agree with this, will work on it.

2017-01-17 09:48 UTC, layershifter commented
TODO: Check for #1169.

2017-01-17 11:34 UTC, layershifter commented on src/elements/Flag/Flag.js
> + **/
Also updated other doc blocks.

2017-01-17 12:13 UTC, layershifter commented
I've updated `commonTests` and all usages of `propKeyOrValueAndKeyToClassName`.

2017-01-17 19:25 UTC, levithomason approved these changes

2017-01-17 19:27 UTC, merged

2017-01-17 20:13 UTC, levithomason commented
Released in `semantic-ui-react@0.64.1`.