Style/proptypes cleanups 2
Semantic-Org/Semantic-UI-React pull request #1159
Opened 2017-01-14 10:55 UTC by layershifter

This PR is part of work for removing propTypes in production bundle (#524, #731).
Also, cleanups and updates typings for #1072.

Affects following components:

- `Container`
- `Divider`
- `Header`
- `Icon`

2017-01-16 16:28 UTC, levithomason requested changes

2017-01-16 16:28 UTC, levithomason commented on src/elements/Header/Header.js
> +    PropTypes.oneOf('top', 'bottom'),
```diff
-PropTypes.oneOf('top', 'bottom'),
+PropTypes.oneOf(['top', 'bottom']),
```

2017-01-16 16:28 UTC, levithomason commented on src/elements/Header/index.d.ts
> +type HEADER_SIZES = 'mini' | 'tiny' | 'small' | 'medium' | 'large' | 'huge'
Looks like this is only used in one place.  Suggest inlining it.

2017-01-16 16:28 UTC, levithomason commented on src/elements/Icon/index.d.ts
>    size?: SemanticSIZES;
I believe this should be `ICON_SIZES`, correct?

2017-01-16 16:31 UTC, layershifter commented
TODO: update `content?: any;` to `React.Node` (`customPropTypes.contentShorthand`).

2017-01-17 09:19 UTC, layershifter commented on src/elements/Icon/index.d.ts
>    size?: SemanticSIZES;
Yep, I also update Group's `propTypes`.

2017-01-17 09:24 UTC, layershifter commented
We need merge #1165 before this, #1165 contains `implementsTextAlignProp` test update.

2017-01-17 19:07 UTC, levithomason approved these changes

2017-01-17 19:08 UTC, levithomason commented
Merged #1165, fixed conflicts and unblocked.  Will merge on pass.

2017-01-17 19:22 UTC, merged

2017-01-17 20:12 UTC, levithomason commented
Released in `semantic-ui-react@0.64.1`.