typings(Popup, Menu): Fixed Popup inverted and MenuItem content types
Semantic-Org/Semantic-UI-React pull request #1164
Opened 2017-01-15 11:30 UTC by dstpierre

2017-01-16 16:15 UTC, levithomason requested changes

2017-01-16 16:15 UTC, levithomason commented on src/collections/Menu/index.d.ts
> +  content?: any;
This is actually `PropTypes.node` which is:

>Anything that can be rendered: numbers, strings, elements or an array (or fragment) containing these types.

https://facebook.github.io/react/docs/typechecking-with-proptypes.html

2017-01-16 16:35 UTC, levithomason commented on src/collections/Menu/index.d.ts
> +  content?: any;
Per @layershifter in https://github.com/Semantic-Org/Semantic-UI-React/pull/1159#issuecomment-272907848, let's use `React.Node`.

2017-01-16 19:56 UTC, dstpierre commented
I used `React.ReactNode` instead of the `any`.

2017-01-16 19:56 UTC, levithomason approved these changes

2017-01-16 19:57 UTC, levithomason commented
Thanks much!

2017-01-16 19:57 UTC, merged

2017-01-17 20:12 UTC, levithomason commented
Released in `semantic-ui-react@0.64.1`.