feat(Button): add `floated` prop to Button.Group
Semantic-Org/Semantic-UI-React pull request #1246
Opened 2017-01-29 02:54 UTC by mohammed88

2017-01-29 03:48 UTC, levithomason requested changes

2017-01-29 03:48 UTC, levithomason commented on test/specs/elements/Button/ButtonGroup-test.js
> +  common.propKeyAndValueToClassName(ButtonGroup, 'float')
Small typo, "floated".

2017-01-29 03:51 UTC, levithomason commented
Thanks for the PR. It would be fantastic to get a doc example for this prop as well!

2017-01-29 04:38 UTC, mohammed88 commented on test/specs/elements/Button/ButtonGroup-test.js
> +  common.propKeyAndValueToClassName(ButtonGroup, 'float')
Typo fixed.

2017-01-29 18:53 UTC, merged

2017-01-29 18:53 UTC, levithomason commented
Thanks much!

2017-01-29 18:55 UTC, layershifter commented
We forget typings there, I'll make PR soon.

2017-01-31 01:20 UTC, levithomason commented
Released in `semantic-ui-react@0.64.5`.