style(Confirm): refactor, update typings and propTypes usage
Semantic-Org/Semantic-UI-React pull request #1282
Opened 2017-02-05 09:45 UTC by layershifter

This PR is part of work for removing propTypes in production bundle (#524, #731).
Also, cleanups and updates typings for #1072.

---

**Warning**. This PR updates behavior of `onCancel` and `onConfirm`, now it handled inside `Confirm` component.

@levithomason I think we need to mark this change as _breaking_.  Before `data` was `Button`'s props while after this PR it will `Confirm`s props.

2017-02-05 14:52 UTC, layershifter commented on src/addons/Confirm/Confirm.js
> +    confirmButton: PropTypes.string,
I'm also thinking about shorthand there too.

```diff
-confirmButton: PropTypes.string,
+confirm: customPropTypes.itemShorthand,
```

2017-02-05 23:13 UTC, levithomason requested changes
Couple changes related to shorthand.  If you'd like to do these in a separate PR, we can do that as well.  LMK.

2017-02-05 23:13 UTC, levithomason commented on src/addons/Confirm/Confirm.js
> +    confirmButton: PropTypes.string,
That would be great if you'd like to implement it. 👍

2017-02-05 23:13 UTC, levithomason commented on src/addons/Confirm/Confirm.js
> +        {createShorthand(Modal.Content, val => ({ children: val }), content)}
I'm slowing trying to remove use of `createShorthand` in favor of adding `create()` methods to the component when needed.  We do plan to have shorthand for the Modal, which we currently don't, so having the `create()` methods for ModalHeader and ModalContent would be helpful.

Let's remove `createShorthand` and add the `create()` method for these components instead.

2017-02-05 23:13 UTC, levithomason commented on src/addons/Confirm/Confirm.js
> +     * Called when the Cancel button is clicked.
Let's correct this, "Called when the Modal is closed without clicking confirm."  Since, it is called on Escape and click outside as well.

2017-02-05 23:13 UTC, levithomason commented on src/addons/Confirm/index.d.ts
> +   * Called when the Cancel button is clicked.
See my comment for the `onClick` propType.

2017-02-05 23:17 UTC, levithomason commented
>**Warning.** This PR updates behavior of onCancel and onConfirm, now it handled inside Confirm component.
>
>@levithomason I think we need to mark this change as breaking. Before data was Button's props while after this PR it will Confirms props.

Thanks, this is how it should've been written initially.  I don't think we'll need to make this one breaking since the previous behavior was a bug and this fixes it.  Also, the callback did not advertise a second `data` parameter, so it was not a supported feature.

2017-02-06 08:33 UTC, layershifter commented on src/addons/Confirm/Confirm.js
> +    confirmButton: PropTypes.string,
Okay, I'll make it today :smile:

2017-02-06 19:16 UTC, layershifter commented
@levithomason I've updated PR, take a look 😄

2017-02-11 06:04 UTC, levithomason approved these changes

2017-02-11 06:04 UTC, merged

2017-02-11 07:01 UTC, levithomason commented
Released in `semantic-ui-react@0.64.8`.