fix(Shape): new Shape component
Semantic-Org/Semantic-UI-React pull request #1323
Opened 2017-02-13 20:25 UTC by tarang9211

2017-02-14 18:01 UTC, tarang9211 commented
@layershifter Could you guide me on this one, if possible? Thanks!

2017-02-17 09:40 UTC, tarang9211 commented
@layershifter Could you give me some feedback when you get a chance?

2017-02-20 12:12 UTC, layershifter requested changes

2017-02-20 12:12 UTC, layershifter commented on src/modules/Shape/Shape.js
> +  AutoControlledComponent as Component,
Let's don't use `AutoControlledComponent` at now, let's back to `React.Component`.

2017-02-20 12:21 UTC, layershifter commented
Let's start from `Shape` sub-components and some props:

```jsx
<Shape.Side active header>Did you know? This side starts visible.</Shape.Side>
//<div class="active ui header side">Did you know? This side starts visible.</div>
```

```jsx
<Shape.Side>
  <Shape.Content center>4</Shape.Content>
</Shape.Side>

<Shape.Side>
  <Shape.Content center='4' />
</Shape.Side>

<Shape.Side center content='4' />

//<div class="side">
//  <div class="content">
//    <div class="center">4</div>
//  </div>
//</div>
```

```jsx
<Shape cube />
//<div class="ui cube shape"></div>
```

```jsx
<Shape type='auto' />
//<div class="ui auto shape"></div>
<Shape type='square' />
//<div class="ui square shape"></div>
<Shape type='auto' />
//<div class="ui irregular shape"></div>
```

2017-02-20 20:09 UTC, tarang9211 commented
@layershifter Can we come up with a list of sub-components and props? I think that would make this easier!

2017-03-07 03:29 UTC, ch3lo commented
I suggest you an update in readme.md marking shape as supported.

2017-03-07 16:31 UTC, levithomason commented
@tarang9211 please see https://github.com/Semantic-Org/Semantic-UI-React/pull/1323#issuecomment-281065710 for subcomponents and props.

2017-03-07 19:22 UTC, tarang9211 commented
@levithomason yup, will have a look. I'm just swamped in the week, will be closing out my open issues by Saturday.

2017-04-10 11:46 UTC, cemremengu commented
Any updates on this ? :eyes:

2017-05-16 19:02 UTC, madwill commented
Hello everyone! Would love to see this component make it into the react implementation! Thank you all for your hard work ! Making the world a prettier place!

2017-05-22 22:48 UTC, levithomason commented
Note, I've just rebased this branch to the latest master to keep it from getting to stale.

2017-05-25 19:40 UTC, madwill commented
Has this been forgotten ?

2017-05-25 21:34 UTC, levithomason commented
It appears @tarang9211 has gotten busy.  We'll gladly take another PR picking up where this one left off.

2017-05-26 20:31 UTC, madwill commented
Thank you for such a quick response, I pulled the fork from tarang but unless i'm not understanding something i don't think we were that close to completion. 

For better understanding of the library and its component, i'll try and give it a shot. Really just at initial stage but i got it to show in the docs with example having shape components and 2 sub components being side and content. 

https://github.com/madwill/Semantic-UI-React/commit/12dc99dd09136a64102d82ac7527bda9dc9ffa25

I confess having currently no idea how to manipulate it to get the semantic ui shape behavior. I'll dig into the official code for it .shape() and .shape('flip X'); as well as other components using javascript for behavior within Semantic-UI-React to see how it already handle such cases. 

I can not make promises as i don't feel confident enough right now but if you could point to a component you feel would be a good example of javascript manipulation without jquery it it may accelerate / make it possible. 

Thank you very much

2017-05-27 08:49 UTC, tarang9211 commented
Hey guys, I'm really sorry for being away! Been extremely busy with work and personal commitments. Happy to help whenever needed.

2017-05-27 13:34 UTC, madwill commented
Turns out is a surprisingly complex component :

https://github.com/Semantic-Org/Semantic-UI/blob/master/src/definitions/modules/shape.js

The way it invokes methods, using query arguments in order to allow for a .shape('flip up') makes it so that its not just re-implementation, it would require some re-engineering. 

With the 6 types of animations requiring adjustments based on component size, its a longer task than expected. 

I get why it stalled. Jquery less semantic UI is an ambitious project considering its implementation. It would even say it has to lose a bit of its "semantic-ism". 

This feels like a lot for a newcomer so i'll let my head cool down.   I don't think i'll be the one creating the pull request. 

Perhaps the flip / stage section will become a bit more clear as i take a step back.

2017-05-27 15:39 UTC, madwill commented
What if we simplify it a bit ? for the sake of quick implement-ability.

Top component (shape) would have 2 props being side and direction

```

    /** Currently displayed side, */
    side: PropTypes.number,

     /** Direction the shape should rotate. */
    direction: PropTypes.oneOf(['right', 'left', 'up', 'down', 'over', 'back']),
```
Usage would be something like this 

```
       <Shape type='auto' side={1} direction='left'>
          <Shape.Side >
            <Image src='https://react.semantic-ui.com/assets/images/avatar/large/matthew.png' />
          </Shape.Side>
          <Shape.Side>
            <Image src='https://react.semantic-ui.com/assets/images/avatar/large/elliot.jpg' />
          </Shape.Side>
        </Shape>
```

User would have to change side by himself with his own controls and state.

We would trigger animation in a life cycle function such as 

```
 componentWillReceiveProps(nextProps) {
    if (nextProps.side !== this.props.side) {
      this.startAnimating()
    }
  }

```
User would still have the liberty to change the "direction" props if that's something someone would want and i would have to make a big "switch" statement in startAnimating to create the correct animation depending on our props and type 

What would be the point of 

`<Shape.Content center='4' />`

It feels like an extra layer that could be avoided, if you look at usage within semantic-ui itself there is no side-content divs. Content is directly written in the side div. 

```
<div class="ui shape">
  <div class="sides">
    <div class="active side">This side starts visible.</div>
    <div class="side">This is yet another side</div>
    <div class="side">This is the last side</div>
  </div>
</div>

```
Let me know what you think

2017-05-30 08:45 UTC, layershifter commented
@madwill Thanks for a detailed suggestions :+1:

My initial idea was about `componentWillReceiveProps`, too. I'll be glad to see changes that realizing this idea.

2017-06-09 10:00 UTC, closed without merging

2017-06-09 12:14 UTC, layershifter commented
I take the PR on myself, #1751