fix(Comment.Group): `size` prop
Semantic-Org/Semantic-UI-React pull request #1327
Opened 2017-02-14 07:42 UTC by tarang9211

2017-02-14 08:13 UTC, layershifter requested changes
And we need add `size` to typings.

2017-02-14 08:13 UTC, layershifter commented on src/views/Comment/CommentGroup.js
> +  size: PropTypes.oneOf(['mini', 'tiny', 'small', 'large', 'big', 'huge', 'massive']),
We use `SIZES` const for definitions, [example](https://github.com/Semantic-Org/Semantic-UI-React/blob/master/src/collections/Message/Message.js#L94).

2017-02-14 08:13 UTC, layershifter commented on test/specs/views/Comment/CommentGroup-test.js
> +    'mini', 'tiny', 'small', 'large', 'big', 'huge', 'massive',
^

2017-02-14 08:53 UTC, tarang9211 commented
@layershifter alright, fixed up. let me know.

2017-02-14 09:37 UTC, layershifter approved these changes

2017-02-14 16:16 UTC, levithomason commented
Fantastic, we just need a doc example for "Group Size" now.  Here are some existing group size doc examples for comparison:

[Examples/elements/Button/GroupVariations/ButtonExampleGroupSize.js](https://github.com/Semantic-Org/Semantic-UI-React/blob/master/docs/app/Examples/elements/Button/GroupVariations/ButtonExampleGroupSize.js)
[Examples/elements/Label/Groups/LabelExampleGroupSize.js](https://github.com/Semantic-Org/Semantic-UI-React/blob/master/docs/app/Examples/elements/Label/Groups/LabelExampleGroupSize.js)
[Examples/views/Statistic/Types/StatisticExampleGroupSize.js](https://github.com/Semantic-Org/Semantic-UI-React/blob/master/docs/app/Examples/views/Statistic/Types/StatisticExampleGroupSize.js)

The comment group size should be listed in `Comment/Variations/CommentExampleGroupSize.js`

2017-02-14 19:54 UTC, tarang9211 commented
@levithomason I've added doc site examples as per your request. Only thing I noticed was that the props for size was listed this way:

<img width="741" alt="screen shot 2017-02-15 at 1 24 14 am" src="https://cloud.githubusercontent.com/assets/5876249/22946490/8872d450-f31d-11e6-8e07-eba76a74d743.png">

2017-02-14 19:55 UTC, tarang9211 commented
@levithomason I think this should wrap up this fix!

2017-02-17 15:43 UTC, levithomason approved these changes

2017-02-17 15:43 UTC, merged

2017-02-17 15:43 UTC, levithomason commented
Thanks again guys!

2017-02-17 17:04 UTC, levithomason commented
Released in `semantic-ui-react@0.65.0`