style(Accordion): update typings
Semantic-Org/Semantic-UI-React pull request #1333
Opened 2017-02-15 16:28 UTC by layershifter

Cleanups and updates typings for #1072.

2017-02-17 16:58 UTC, levithomason requested changes

2017-02-17 16:58 UTC, levithomason commented on src/modules/Accordion/index.d.ts
> +  onConfirm?: (event: React.MouseEvent<HTMLDivElement>, data: AccordionTitleProps) => void;
Whoops, confirm here.

2017-02-17 17:13 UTC, layershifter commented
Copy-paste is evil 😄

2017-02-21 00:06 UTC, levithomason approved these changes

2017-02-21 00:06 UTC, merged

2017-02-22 02:05 UTC, levithomason commented
Released in `semantic-ui-react@0.66.0`.