fix(Progress): do not show progress without progress or label props
Semantic-Org/Semantic-UI-React pull request #1355
Opened 2017-02-20 16:40 UTC by BrainMaestro

Fix #1352

2017-02-20 16:54 UTC, layershifter requested changes

2017-02-20 16:54 UTC, layershifter commented on src/modules/Progress/Progress.js
>      if (label || progress || !_.isUndefined(precision)) return true
Let's make this condition more simple:

```diff
-if (label || progress || !_.isUndefined(precision)) return true
+return label || progress || !_.isUndefined(precision)
```

2017-02-20 16:55 UTC, BrainMaestro commented on src/modules/Progress/Progress.js
>      if (label || progress || !_.isUndefined(precision)) return true
Sure. I noticed it, but I didn't want to make changes that were not directly related to the task. I'll do that now

2017-02-20 16:59 UTC, layershifter approved these changes
@BrainMaestro Thanks for PR 👍

2017-02-21 00:02 UTC, levithomason commented
# Issue
I think we need to rework the relationship of the `progress` and `label` props altogether.

1. SUI core offers a `label` setting, which takes a value of `percent` or `ratio`.  This is where we got our prop `label`.  However, this is super confusing since the `label` prop controls the `progress` readout, and the `children` control the actual `label` component.

2. It also makes for this very confusing case where the `label` boolean prop does exactly the same thing as the boolean`progress` prop:

    ![http://g.recordit.co/iN1aOdD1MR.gif](http://g.recordit.co/iN1aOdD1MR.gif)

# Fix Proposal
I think we need to make the `progress` prop control the progress readout and make the `label` prop control the label component.

![image](https://cloud.githubusercontent.com/assets/5067638/23145714/493152d2-f785-11e6-936b-e54483b4578b.png)

This would be more inline with our prop-to-subcomponent relationship we have across the entire library as well.
***
Thoughts?

2017-02-21 07:31 UTC, BrainMaestro commented
@levithomason I agree. That makes it clearer. The other way was slightly confusing.

2017-02-21 16:27 UTC, levithomason commented
Awesome.  Here are some pointers are how to handle the new propTypes and values.  The `label` prop is now a "shorthand" prop used to create the label element.  We should start with propTypes like so:

```jsx
    /** Can be set to either to display progress as percent or ratio. */
    label: customPropTypes.itemShorthand,

    /** A progress bar can contain a text value indicating current progress. */
    progress: PropTypes.oneOfType([
      PropTypes.bool,
      PropTypes.oneOf(['ratio', 'percent']),
    ]),
```

The `itemShorthand` allows users to pass a number, string, props object, or an element from which we will then create an element for them.  In this case we'll create the `className='label'` div.

We have a factory function for doing this called, `createShorthand`.  You get it by adding it to the `lib` import:

```jsx
import { createShorthand } from '../../lib'
```

This function takes an element class (string or function), a function to map number/string values to props, and finally the value you want to create an element with (number, string, props object, or another element).  Create a `labelElement` in the render method (comments can be left out):

```jsx
const labelElement = createShorthand(
  'div',                                // create a div
  val => ({ children: val }),           // map string/numbers to children
  label,                                // use the label prop as the value
  { className: 'label' }                // default props
)
```

Now, we can conditionally display the `children` or the `labelElement`, whichever the user passed.

```diff
-{children && <div className='label'>{children}</div>}
+{children ? <div className='label'>{children}</div> : labelElement}
```

2017-02-22 13:55 UTC, BrainMaestro commented
Hey @levithomason. Thanks for the task breakdown. I implemented it exactly as you suggested, but the check `{children ?` fails for any falsy value which includes `0` that is used in the `renders child number with 0 value` test. Should I use `!_.isUndefined` in the render function which is how I solved the problem? Or do you have a cleaner approach?

2017-02-22 22:38 UTC, levithomason commented
We've updated the code base to use `_.isNil(children)` so as to capture `null` and `undefined`.

2017-02-23 13:46 UTC, BrainMaestro commented
Okay has it been merged in?

2017-02-23 13:48 UTC, BrainMaestro commented on src/modules/Progress/Progress.js
> +        {!_.isUndefined(children) ? <div className='label'>{children}</div> : labelElement}
This is the line I was talking about. Can I safely change it to `{children ? <div className='label'>{children}</div> : labelElement}` without the false positives of `0` failing the truthy check?

2017-02-23 13:54 UTC, layershifter commented on src/modules/Progress/Progress.js
> +        {!_.isUndefined(children) ? <div className='label'>{children}</div> : labelElement}
```diff
- {!_.isUndefined(children) ? <div className='label'>{children}</div> : labelElement}
+ {_.isNil(children) ? this.getLabel() : <div className='label'>{children}</div>}
```

2017-02-23 13:57 UTC, BrainMaestro commented on src/modules/Progress/Progress.js
> +        {!_.isUndefined(children) ? <div className='label'>{children}</div> : labelElement}
okay the label should take priority over the children? I thought it was the reverse. I will make the change

2017-02-23 14:21 UTC, layershifter commented on src/modules/Progress/Progress.js
> +        {!_.isUndefined(children) ? <div className='label'>{children}</div> : labelElement}
```jsx
{_.isNil(children) ? this.getLabel() : <div className='label'>{children}</div>}
{!_.isNil(children) ? <div className='label'>{children}</div> : this.getLabel()}
```

There conditions do same, but first looks more simplier to me.

These conditions

2017-02-23 14:37 UTC, layershifter requested changes

2017-02-23 14:37 UTC, layershifter commented on src/modules/Progress/Progress.js
> +        {!_.isNil(children) ? <div className='label'>{children}</div> : this.getLabel()}
I think we can move this condition to `getLabel`:

```diff
-  getLabel = () => {
-    const { label } = this.props
-
-    return createShorthand(
-      'div',
-      val => ({ children: val }),
-      label,
-      { className: 'label' }
-    )
-  }
+ renderLabel = () => {
+   const { children, label } = this.props
+   
+   if(!_.isNil(children)) return <div className='label'>{children}</div>

+    return createShorthand(
+      'div',
+      val => ({ children: val }),
+      label,
+      { className: 'label' }
+    )
+ }

2017-02-23 14:37 UTC, layershifter commented on src/modules/Progress/Progress.js
>              </div>
And this to `renderProgress`:

```diff
- {this.showProgress() && (
-  <div className='progress'>
-    { progress !== 'ratio' ? `${percent}%` : `${value}/${total}` }
-  </div>
- })
+ {this.renderProgress()}
```

```diff
+ renderProgress = () => {
+   const { precision, progress } = this.props
+
+   if(!progress && _.isUndefined(precision)) return
+   return (
+     <div className='progress'>
+      { progress === 'ratio' ? `${value}/${total}` : `${percent}%` }
+    </div>
+   )
+}
```

2017-02-23 15:16 UTC, layershifter approved these changes

2017-02-23 23:21 UTC, levithomason commented
Excellent!

2017-02-23 23:21 UTC, merged

2017-02-23 23:23 UTC, levithomason commented
This is a breaking change, so we need to update the PR title and description to include upgrade notes.  Reference #1367 or #989 for good examples.

2017-03-01 06:33 UTC, levithomason commented
Thanks for the great notes @BrainMaestro 👍

2017-03-01 07:36 UTC, levithomason commented
Released in `semantic-ui-react@0.67`.