docs(Progress): added example for progress label prop
Semantic-Org/Semantic-UI-React pull request #1356
Opened 2017-02-20 17:07 UTC by tarang9211

Fixes #1351

2017-02-20 17:09 UTC, layershifter requested changes

2017-02-20 17:09 UTC, layershifter commented on docs/app/Examples/modules/Progress/Content/ProgressExampleLabel.js
> +    <Progress value='4' total='5' label='percent' />
Let's split these examples to separate files.

2017-02-20 17:12 UTC, layershifter commented
Let's point these examples in `Content` section under `Progress` example. Small description for them will be awesome.

2017-02-20 17:17 UTC, tarang9211 commented
@layershifter Have a look at the recent commit and let me know if you still would like changes.

2017-02-20 17:24 UTC, layershifter requested changes

2017-02-20 17:24 UTC, layershifter commented on docs/app/Examples/modules/Progress/Content/ProgressExampleLabel.js
> -  <Progress percent={55}>Label</Progress>
Let's return this example, it shows another behaviour. However, there is #1355 that fixes bug, so we need a small update there:

```diff
-<Progress percent={55}>Label</Progress>
+<Progress percent={55} label>Label</Progress>
```

2017-02-20 17:24 UTC, layershifter commented on docs/app/Examples/modules/Progress/Content/index.js
> +      examplePath='modules/Progress/Content/ProgressExampleLabelRatio'
Let's add descriptions:
- for `LabelPercent`: A progress element can contain a percent label.
- for `LabelRatio`: A progress element can contain a ratio label.

2017-02-20 17:27 UTC, tarang9211 commented on docs/app/Examples/modules/Progress/Content/index.js
> +      examplePath='modules/Progress/Content/ProgressExampleLabelRatio'
What should be the title of these sections?

2017-02-20 17:29 UTC, layershifter commented on docs/app/Examples/modules/Progress/Content/index.js
> +      examplePath='modules/Progress/Content/ProgressExampleLabelRatio'
`description='A progress element can contain a percent label.'`

2017-02-20 17:32 UTC, tarang9211 commented on docs/app/Examples/modules/Progress/Content/index.js
> +      examplePath='modules/Progress/Content/ProgressExampleLabelRatio'
Sounds good, got it.

2017-02-20 17:35 UTC, tarang9211 commented
Oops sorry for that, I copied the wrong thing.

2017-02-20 17:44 UTC, layershifter approved these changes

2017-02-20 23:44 UTC, levithomason requested changes

2017-02-20 23:44 UTC, levithomason commented on docs/app/Examples/modules/Progress/Content/ProgressExampleLabel.js
> +  <Progress percent={55} label>Label</Progress>
The label prop is not required here.  This is confusing on SUI core's part, however, the label prop controls the label **inside of the bar** while the `Label` child here is the label **below the progress bar**:

![image](https://cloud.githubusercontent.com/assets/5067638/23145472/4efbdd24-f783-11e6-823c-4601dfb2ff8d.png)


I feel like these should almost have separate names so it is more clear that there are two different label positions (in the bar, under the bar).

2017-02-21 00:45 UTC, levithomason approved these changes

2017-02-21 00:46 UTC, merged