fix(Dropdown|Modal|TextArea): update refs handlers
Semantic-Org/Semantic-UI-React pull request #1360
Opened 2017-02-21 09:20 UTC by layershifter

Addresses #607.

2017-02-21 17:35 UTC, levithomason requested changes

2017-02-21 17:35 UTC, levithomason commented on src/addons/TextArea/TextArea.js
> +  handleRef = c => (this.rootNode = c)
Nice, we should also standardize these ref variable names.  We currently use `*Node`, `_*` and `*Ref` in various places.

A ref can either be a node (DOM component) or a reference to a class instance (Composite component).  Due to this, I vote we go with `this.*Ref` for clarity and accuracy.

2017-02-21 19:16 UTC, layershifter commented on src/addons/TextArea/TextArea.js
> +  handleRef = c => (this.rootNode = c)
Yep, it makes sense 👍

Do I havу to change the names to these?
```diff
-handleRef = c => (this.rootNode = c)
+handleRef = c => (this.textAreaRef = c)
```
```diff
-handleSearchRef = c => (this._search = c)
+handleSearchRef = c => (this._searchRef = c)
```

2017-02-21 21:28 UTC, levithomason commented on src/addons/TextArea/TextArea.js
> +  handleRef = c => (this.rootNode = c)
Looks right to my eyes 👍

2017-02-22 00:42 UTC, levithomason approved these changes

2017-02-22 00:43 UTC, levithomason commented
I've updated the refs per our agreement.  Refs at the root I simply used `this.ref` and `this.handleRef` for the naming convention.  Mirrors how we handle `onClick``this.handleClick` vs `onItemClick``this.handleItemClick`.

Give it a look over and let me know if we're good to go here.

2017-02-22 08:22 UTC, layershifter commented
I've updated `Checkbox` handler. LGTM :+1:

2017-02-22 22:38 UTC, merged

2017-03-01 07:36 UTC, levithomason commented
Released in `semantic-ui-react@0.67`.