fix(Button): update handling of floated prop
Semantic-Org/Semantic-UI-React pull request #1489
Opened 2017-03-21 12:06 UTC by layershifter

Fixes #1488.

`floated` class must be on wrapper if we have `Label` element, this PR update handling of this.

2017-03-21 12:07 UTC, layershifter commented on src/elements/Button/Button.js
> -    })
I've moved this inline function to method, so it will not be created on each render.

2017-03-24 03:09 UTC, levithomason requested changes

2017-03-24 03:09 UTC, levithomason commented on test/specs/elements/Button/Button-test.js
> +    it('contains children without floated class when floated attribute is set', () => {
Would prefer we assert the expected location of the floated class in this test as well. It currently asserts where the className should _not_ be, but doesn't assert where it _should_ be.

2017-03-24 08:32 UTC, layershifter commented on test/specs/elements/Button/Button-test.js
> +    it('contains children without floated class when floated attribute is set', () => {
I've updated tests as you requested :+1:

2017-03-25 03:41 UTC, levithomason approved these changes

2017-03-25 03:41 UTC, merged

2017-03-25 04:12 UTC, levithomason commented
Released in `semantic-ui-react@0.67.2`.