fix(Dropdown):handle click on dropdown when search result is empty
Semantic-Org/Semantic-UI-React pull request #1490
Opened 2017-03-21 14:04 UTC by rajchourasia

Fixes #1451 . Mimics the behaviour of SUI core in similar scenario.

2017-03-23 08:24 UTC, layershifter requested changes

2017-03-23 08:24 UTC, layershifter commented on src/modules/Dropdown/Dropdown.js
> +    return this.open(e)
Can we simplify logic there?

```js
toggle = (e) => {
  if (this.state.open) {
    this.open(e)
    return
  }

  const { search } = this.props
  const options = this.getMenuOptions()

  if (search && _.isEmpty(options)) {
    e.preventDefault()
    return
  }

  this.close(e)
}
```

It looks more readable to me.

2017-03-23 08:43 UTC, layershifter approved these changes

2017-03-25 03:47 UTC, levithomason commented
Thanks for writing a test for this as well.  This is a good stop-gap for now, however, the SUI core dropdown still allows toggling an empty search dropdown when the icon is clicked:

![http://g.recordit.co/QrNPOXFFtr.gif](http://g.recordit.co/QrNPOXFFtr.gif)

We should address that at some point.

2017-03-25 03:51 UTC, merged

2017-03-25 04:12 UTC, levithomason commented
semantic-ui-react@0.67.2