fix(Progress): Floor data-percent attribute (#1671)
Semantic-Org/Semantic-UI-React pull request #1672
Opened 2017-05-12 02:37 UTC by patrickgaskill

Floor the data-percent attribute so Semantic UI CSS works as expected.

Fixes #1671

2017-05-12 05:18 UTC, layershifter requested changes
@patrickgaskill Thanks for PR. It will be awesome to get a test there that asserts that `Math.floor` was done.

2017-05-12 15:15 UTC, layershifter approved these changes

2017-05-12 15:27 UTC, levithomason commented
Superb! Thanks, folks!

2017-05-13 18:54 UTC, merged

2017-05-27 20:08 UTC, levithomason commented
Released in `semantic-ui-react@0.68.4`.