Feat(TextArea) add minHeight property, docs example
Semantic-Org/Semantic-UI-React pull request #1679
Opened 2017-05-14 17:27 UTC by josie11

Adds minHeight property to TextArea that can be used with autoHeight property to specify a minimum number of rows a TextArea should have. Referenced here: [#1647](https://github.com/Semantic-Org/Semantic-UI-React/issues/1647).

I've implemented this by setting ```this.ref.rows = minHeight```, but I'm not sure if this is the ideal way. I'd have to adjust ```assertHeight``` in the [tests](https://github.com/Semantic-Org/Semantic-UI-React/blob/master/test/specs/addons/TextArea/TextArea-test.js#L68) in order to add a test for it.

2017-05-15 15:36 UTC, layershifter commented on src/addons/TextArea/TextArea.js
> +    this.ref.rows = minHeight
`minHeight` prop should affect next line,  `rows` should be also customizable:

```diff
static defaultProps = {
   as: 'textarea',
+  minHeight: 0,
+  rows: 5,
}
```

```diff
-this.ref.rows = minHeight
-this.ref.style.minHeight = '0'
+this.ref.style.minHeight = minHeight + 'px'
```

```diff
render() {
-  const { value } = this.props
+  const { rows, value } = this.props
// ...
- return <ElementType{...rest} onChange={this.handleChange} ref={this.handleRef} value={value} />
+  return (
+    <ElementType
+      {...rest} 
+      onChange={this.handleChange}
+      ref={this.handleRef}
+      rows={rows}
+      value={value}
+    />
+  )
}
```

2017-05-15 15:37 UTC, layershifter requested changes
Thanks for PR. I think that `rows` should be also customizable:

```diff
static defaultProps = {
   as: 'textarea',
+  minHeight: 0,
+  rows: 5,
}
```

```diff
-this.ref.rows = minHeight
-this.ref.style.minHeight = '0'
+this.ref.style.minHeight = minHeight + 'px'
```

```diff
render() {
-  const { value } = this.props
+  const { rows, value } = this.props
// ...
- return <ElementType{...rest} onChange={this.handleChange} ref={this.handleRef} value={value} />
+  return (
+    <ElementType
+      {...rest} 
+      onChange={this.handleChange}
+      ref={this.handleRef}
+      rows={rows}
+      value={value}
+    />
+  )
}
```

2017-05-15 16:57 UTC, josie11 commented
I added the ```rows``` prop but I left it in ```updateHeight``` & usable with ```autoHeight``` for now - otherwise it will break tests. Also, when using autoHeight it seems the intended default rows should be 1, so there is a conflict there.

2017-05-18 11:06 UTC, layershifter approved these changes
I've pushed some changes there, LGTM.

However, there is one breaking change with `autoHeight`. Before these changes `rows` prop had `1` value, now it's has `3` by default.

2017-05-22 17:39 UTC, levithomason commented
Reviewing the code changes, it strikes me odd that we're pulling `autoHeight` up to a prop.  Perhaps it makes more sense to leave this in the style prop:

```jsx
<TextArea style={{ minHeight: 100 }} />
```

2017-05-23 09:37 UTC, layershifter commented
@levithomason Thanks for the feedback, I'll make these changes.

2017-05-25 07:43 UTC, layershifter approved these changes
I've performed there some changes. `minHeight` was back to style :+1:

2017-06-07 16:19 UTC, levithomason approved these changes
Thanks much @josie11 and @layershifter!

2017-06-07 16:19 UTC, merged

2017-06-22 01:26 UTC, levithomason commented
Released in `semantic-ui-react@0.69.0`