feat(Search): noResultsMessage prop can be a node
Semantic-Org/Semantic-UI-React pull request #1683
Opened 2017-05-16 18:40 UTC by b0gok

PR for this issue https://github.com/Semantic-Org/Semantic-UI-React/issues/1664

2017-05-18 15:41 UTC, levithomason requested changes
Just one comment regarding propTypes and typings.

2017-05-18 15:41 UTC, levithomason commented on src/modules/Search/Search.js
> +    ]),
I believe this should just be `PropTypes.node` only.  `PropTypes.node` includes any renderable value: string, number, element, or an array (or fragment) of any of these.  However, objects are not renderable.

Let's also update the typings in `Search.d.ts` to reflect the type change as well.

2017-05-18 21:13 UTC, b0gok commented on src/modules/Search/Search.js
> +    ]),
> PropTypes.node includes any renderable value: string, number, element, or an array (or fragment) of any of these. 

Didn't know about it. Thanks for useful information. Made the necessary changes.

2017-05-21 08:33 UTC, layershifter requested changes

2017-05-21 08:33 UTC, layershifter commented on src/modules/Search/Search.d.ts
>    noResultsDescription?: string;
@b0gok Thanks for a PR. I think that we need make same changes for `noResultsDescription`.

2017-05-21 21:14 UTC, b0gok commented on src/modules/Search/Search.d.ts
>    noResultsDescription?: string;
@layershifter Should I add specific test for case when noResultsDescription isn't a string?

2017-05-22 06:57 UTC, layershifter commented on src/modules/Search/Search.d.ts
>    noResultsDescription?: string;
Yes, it will be awesome.

2017-05-22 17:29 UTC, levithomason approved these changes

2017-05-22 17:30 UTC, levithomason commented
Thank you for the PR and updates!

2017-05-22 17:30 UTC, merged

2017-05-27 20:07 UTC, levithomason commented
Released in `semantic-ui-react@0.68.4`.