Add Tab definitions
Semantic-Org/Semantic-UI-React pull request #1808
Opened 2017-06-29 11:53 UTC by pierre-H

2017-06-29 13:04 UTC, layershifter requested changes

2017-06-29 13:04 UTC, layershifter commented on index.d.ts
> +
The `Tab` has also the `TabPane` subcomponent, let's export it, too

2017-06-29 14:02 UTC, pierre-H commented on index.d.ts
> +
@layershifter You're right ! It's done.

2017-06-29 14:17 UTC, layershifter approved these changes
@pierre-H Thanks for update, LGTM

2017-06-30 16:39 UTC, merged

2017-07-07 17:07 UTC, levithomason commented
Released in `semantic-ui-react@0.71.0`.