style(typings): Add panes prop definition
Semantic-Org/Semantic-UI-React pull request #1812
Opened 2017-06-29 14:45 UTC by pierre-H

2017-06-30 06:39 UTC, layershifter requested changes

2017-06-30 06:39 UTC, layershifter commented on src/modules/Tab/Tab.d.ts
> +  panes?: Array<{menuItem: string; render: () => React.ReactNode;}>;
Can we make it multiline?

```ts
panes?: Array<{
  menuItem: string;
  render: () => React.ReactNode;
}>;
```

2017-06-30 06:47 UTC, pierre-H commented on src/modules/Tab/Tab.d.ts
> +  panes?: Array<{menuItem: string; render: () => React.ReactNode;}>;
@layershifter done

2017-06-30 06:55 UTC, layershifter reviewed
@pierre-H Thanks again, LGTM

2017-06-30 15:07 UTC, layershifter commented
I've relaxed type for changes from #1823.

2017-06-30 16:39 UTC, merged

2017-07-07 17:07 UTC, levithomason commented
Released in `semantic-ui-react@0.71.0`.