feat(Search): prop to return the active result
Semantic-Org/Semantic-UI-React pull request #1825
Opened 2017-07-02 15:39 UTC by treyhuffine

Return the active value in `<Search>` when navigating using the arrow keys

2017-07-03 11:14 UTC, layershifter commented on src/modules/Search/Search.js
> +    onActiveSelectionChange: PropTypes.func,
I think that `onActiveSelectionChange` can be renamed to `onSelectionChange`.

2017-07-03 11:21 UTC, layershifter requested changes
@treyhuffine thanks for PR. 

I left some feedback, it will awesome if we will also add new test for the prososed callback.

2017-07-03 11:21 UTC, layershifter commented on src/modules/Search/Search.js
> +    if (onActiveSelectionChange) onActiveSelectionChange(result)
We can exclude there if-condition if we will use lodash's `invoke`. Also, our callbacks should return `props` as the second argument.

```js
_.invoke(this.props, `onActiveSelectionChange`, e, { ...this.props, result})
```

2017-07-04 02:37 UTC, treyhuffine commented
@layershifter thanks, I'll fix and resubmit.

2017-07-04 06:59 UTC, layershifter commented
@treyhuffine Thanks 👍 You can simply push your commits into the current branch instead of the new PR

2017-07-11 11:06 UTC, layershifter commented on src/modules/Search/Search.js
> +        this.moveSelectionBy(e, 1)
We will need `e` in `handleSelectionChange`.

2017-07-11 11:06 UTC, layershifter commented on src/modules/Search/Search.d.ts
> +  onResultSelect?: (event: React.MouseEvent<HTMLDivElement>, data: SearchResultData) => void;
`data` there also contains `result`.

2017-07-11 11:07 UTC, layershifter approved these changes
@levithomason we're for review there.

2017-08-10 21:30 UTC, merged

2017-08-12 05:37 UTC, levithomason commented
Released in `semantic-ui-react@0.71.4`