feat(Dropdown): lazy load options
Semantic-Org/Semantic-UI-React pull request #1918
Opened 2017-08-01 23:05 UTC by dsirnk

Lazy-loading options will be very useful and efficient when there are many options.
We could eventually bind it to a prop like 'lazyLoad={true}'.

2017-08-03 23:31 UTC, dsirnk commented
Sorry this is my first PR ever.

Anyone know what the issue is here?
I made the change so that the _dropdown_ only populates with options when it's open (lazy loading).
I made respective changes to the unit tests to account for the change. And ensuring that all the tests pass.

However, I don't know what **codecov** is and why the **_codecov/patch_** and **_codecov/project_** are failing.

2017-08-10 20:40 UTC, levithomason commented
Codecov seems to be broken.  It measures code coverage in our project.  They changed how they calculate that recently and it hasn't recovered.  You can safely ignore it for now.

2017-08-10 20:45 UTC, levithomason commented on test/specs/modules/Dropdown/Dropdown-test.js
> +        // .should.have.prop('active', true)
I would think re-opening the dropdown would retain the active item.  You could simply try something like (untested):

```jsx
wrapper
  .find('DropdownItem')
  .first()
  .simulate('click')

// re-open the dropdown
wrapper.setProps({ open: true })

wrapper
  .find('DropdownItem')
  .first()
  .should.have.prop('active', true)
```

2017-08-10 20:46 UTC, levithomason requested changes
Would like to resolve https://github.com/Semantic-Org/Semantic-UI-React/pull/1918#discussion_r132563071 before merge.

2018-06-19 13:19 UTC, levithomason commented
I've rebased this to master, moved the logic to a `lazyLoad` prop, and cleaned up tests.  This can be merged after tests pass and a review is done.

2018-06-19 13:20 UTC, levithomason approved these changes

2018-06-26 00:59 UTC, merged

2018-06-26 01:37 UTC, levithomason commented
Released in `semantic-ui-react@0.81.2`.

2018-07-04 11:52 UTC, hubertguillemain commented
I just created a bug (#2975) , as I don't see this working as I would expect.
But maybe I'm doing it wrong?
If so, can you please explain and add a sample usage to the doc site ?