style(tests): mixed lint updates
Semantic-Org/Semantic-UI-React pull request #1939
Opened 2017-08-07 14:51 UTC by layershifter

This PR contains only styling changes, it was splitted from #1895 to simplify review.

2017-08-10 21:03 UTC, levithomason commented on test/specs/commonTests/isConformant.js
> +            JSON.stringify(handlerSpy.args, null, 2)}`,
Hm, looks like the update here went awry.

2017-08-10 21:05 UTC, levithomason commented on test/specs/lib/numberToWord-test.js
> +    words.forEach(word => numberToWord(word).should.equal(word))
Why is it that in some (most?) cases the parens are added, but in others they are removed?

https://github.com/Semantic-Org/Semantic-UI-React/pull/1939/files#diff-ca99bb99c3b7ee63716bc6db755e5413R107

https://github.com/Semantic-Org/Semantic-UI-React/pull/1939/files#diff-ca99bb99c3b7ee63716bc6db755e5413R107

..etc

2017-08-10 21:07 UTC, levithomason commented on test/tests.bundle.js
> +let runnable = testsContext.keys().filter(path => __karmaWebpackManifest__.indexOf(path) >= 0)
Here's another example where parens are removed while most others are added.

2017-08-10 21:08 UTC, levithomason requested changes
I believe there is syntax error in `isConformant.js`, see inline comment.

Other than this, it seems the style is also inconsistent between files (arrow func arg parens).  That said, I'd rather implement `eslint` rules that fixable for these so we don't have to manage them ourselves.

2017-08-10 21:08 UTC, layershifter commented on test/specs/lib/numberToWord-test.js
> +    words.forEach(word => numberToWord(word).should.equal(word))
https://github.com/airbnb/javascript#arrows--implicit-return

2017-08-10 21:09 UTC, layershifter commented on test/specs/commonTests/isConformant.js
> +            JSON.stringify(handlerSpy.args, null, 2)}`,
Yep, should be fixed. Will fix tomorrow

2017-08-10 21:12 UTC, layershifter commented
@levithomason  this come from airbnb rules, I gave link in a comment:

> If the function body consists of a single statement returning an expression without side effects, omit the braces

2017-08-10 21:21 UTC, levithomason commented
That would refer to the curly braces of the function body`{}`, I'm referring to the parentheses of the arguments `()`.

When there is a single argument, the changes here arbitrarily add parens in some cases and remove them in other cases.   I can't seem to figure out what the reason is.

**tests.bundle.js** (Removes parens)
```diff
-.filter((path) =>
+.filter(path =>
```

**test/specs/views/Feed/FeedEvent-test.js** (Adds parens)
```diff
-contentProps.forEach(propKey => {
+contentProps.forEach((propKey) => {
```

**test/specs/lib/numberToWord-test.js** (Removes parens)
```diff
-words.forEach((word) =>
+words.forEach(word =>
```

**test/specs/behaviors/Visibility/Visibility-test.js** (Adds parens)
```diff
-expectations.forEach(expectation => {
+expectations.forEach((expectation) => {
```

...there are many of these in the PR.

2017-08-11 14:12 UTC, layershifter commented
@levithomason This code was automatically fortmatted with `eslint` and `airbnb` preset. I split #1895 to smaller PRs only for review purposes.

It looks confusing, but it's correct. Take a look [8.2](https://github.com/airbnb/javascript#arrows--implicit-return), this paragraph affects `arrow-parens` rule, too.

```js
// bad
[1, 2, 3].map(number => {
  const nextNumber = number + 1;
  `A string containing the ${nextNumber}.`;
});

// good
[1, 2, 3].map(number => `A string containing the ${number}.`);

// good
[1, 2, 3].map((number) => {
  const nextNumber = number + 1;
  return `A string containing the ${nextNumber}.`;
});

// good
[1, 2, 3].map((number, index) => ({
  [index]: number,
}));
```

Paragraph [8.4](https://github.com/airbnb/javascript#arrows--one-arg-parens) also describes behaviour of parentheses.

```js
// bad
[1, 2, 3].map((x) => x * x);

// good
[1, 2, 3].map(x => x * x);
```

2017-08-11 14:25 UTC, layershifter commented on test/specs/commonTests/isConformant.js
> +            JSON.stringify(handlerSpy.args, null, 2)}`,
I've fixed this.

2017-08-11 14:26 UTC, layershifter reviewed
@levithomason I've fixed formatting of that message and answered about parens.

2017-08-13 16:57 UTC, levithomason commented
Got it, thank you again.  I'm OK with this so long as it is fully automated.  👍

2017-08-13 16:57 UTC, merged

2017-08-20 20:58 UTC, levithomason commented
Released in `semantic-ui-react@0.71.5`