Adds prop for clearing searchQuery data on item select or on enter
Semantic-Org/Semantic-UI-React pull request #1955
Opened 2017-08-11 19:20 UTC by creedmangrum

I wanted to add a prop to the dropdown where the search query could be cleared after selection on the multiple select, if desired. 

This maintains the current behavior of how everything works today, but if the prop is added then the search query will clear after item selection. 

I asked this question [here](https://github.com/Semantic-Org/Semantic-UI-React/issues/1954) on issue #1954 but just figured it was easy enough to PR before waiting for an answer.

2017-08-13 16:50 UTC, levithomason commented on src/modules/Dropdown/Dropdown.d.ts
> +  searchQueryClearOnSelect?: boolean;
Nit: Could we go with `clearSearchQueryOnSelect`?

2017-08-13 16:52 UTC, levithomason requested changes
I've requested a prop name change above.  We just need some tests for this prop:

```js
describe('clearSearchQueryOnSelect', () => {
  it('does not clear the query by default on item click', () => {})
  
  it('does not clear the query by default on enter', () => {})
  
  it('clears the query on item click', () => {})
  
  it('clears the query on enter', () => {})
})
```

2017-08-14 15:09 UTC, creedmangrum commented on src/modules/Dropdown/Dropdown.d.ts
> +  searchQueryClearOnSelect?: boolean;
not a nit at all, was hoping for some specific feedback on the naming anyway. i just put it near the search ones as it felt grouped, but really was unsure about naming convention. will switch to your suggestion.

2017-08-14 15:10 UTC, creedmangrum commented
thanks for the feedback. will add the tests and prop name change.

2017-08-14 18:53 UTC, creedmangrum commented
okay should be good to go!

2017-08-20 17:05 UTC, levithomason commented on test/specs/modules/Dropdown/Dropdown-test.js
> +      wrapper.should.have.state('searchQuery', searchQuery)
Comment needs updated, or removed :)

2017-08-20 17:05 UTC, levithomason commented on test/specs/modules/Dropdown/Dropdown-test.js
> +      wrapper.should.have.state('searchQuery', searchQuery)
Comment out of date

2017-08-20 17:09 UTC, levithomason requested changes
There are a couple out of date comments that should be updated or removed.

We merge another PR which handles clearing the search query when there is only one option.  This PR has some conflicts that need to be resolved.

2017-08-21 00:27 UTC, creedmangrum commented
Great taken care of. Sorry about the bad comments in the tests. Whoops.

2017-08-22 14:39 UTC, creedmangrum commented
I think that the other PR that was merged probably solves for the use case, where the search query should be cleared if it is the available options === 1. I am likely going to close this, unless you feel that it still makes sense to do.

2017-08-27 22:26 UTC, levithomason commented
Fewer options in the Dropdown, the happy I am 😄!  This component is quite complex and getting hairy to work on.

Assuming we're all good here, I'll take your suggestion and close this.  Let me know if we need to reopen it.

2017-08-27 22:26 UTC, closed without merging