fix(Search): only call onBlur & onFocus event handler once
Semantic-Org/Semantic-UI-React pull request #1963
Opened 2017-08-14 15:33 UTC by chopstikk

fix for #1962 

Search component onBlur and onFocus event handers should not be called twice.

2017-08-15 07:51 UTC, layershifter requested changes
@chopstikk Thanks for PR. However, I think that we should add tests there to omit such cases in future.

Something like:
```js
describe('onFocus', () => {
  it('is called with (e, data)', () => {
    const onFocus = sandbox.spy()
    wrapperMount(<Search onFocus={onFocus} />)
    
    wrapper.simulate('focus')

    onFocus.should.have.been.calledOnce()
    onFocus.should.have.been.calledWithMatch({ }, { options })
  })
})
```

2017-08-15 11:15 UTC, layershifter requested changes

2017-08-15 11:15 UTC, layershifter commented on test/specs/modules/Search/Search-test.js
> +      const spy = sandbox.spy()
Please name `spy` as event handler, i.e. `onBlur`.

2017-08-15 11:15 UTC, layershifter commented on test/specs/modules/Search/Search-test.js
> +      spy.should.have.been.calledWithMatch(nativeEvent)
Let's also check that second argument provides a valid props:

```diff
-wrapperMount(<Search onBlur={spy} />)
+wrapperMount(<Search onBlur={spy} results={options} />)

-spy.should.have.been.calledWithMatch(nativeEvent)
+spy.should.have.been.calledWithMatch(nativeEvent, { onBlur, results: options })
```

2017-08-15 11:15 UTC, layershifter commented on test/specs/modules/Search/Search-test.js
> +    it('is called with (event) on search input blur', () => {
Let's also correct a title `is called with (e, data) on...`

2017-08-16 08:34 UTC, layershifter approved these changes

2017-08-20 16:14 UTC, merged

2017-08-20 16:14 UTC, levithomason commented
I love you two, thanks! 😄

2017-08-20 20:58 UTC, levithomason commented
Released in `semantic-ui-react@0.71.5`