fix(Sticky|Visibility): add null check on window
Semantic-Org/Semantic-UI-React pull request #1990
Opened 2017-08-21 18:21 UTC by ChrisNLott

fix(Sticky|Visibility): add null check on window for server side rendering

fixes https://github.com/Semantic-Org/Semantic-UI-React/issues/1987

2017-08-22 10:33 UTC, layershifter requested changes

2017-08-22 10:33 UTC, layershifter commented on src/behaviors/Visibility/Visibility.js
> +    context: isBrowser ? window : {},
Let's use `null` there:
```js
isBrowser ? window : null,
```

2017-08-22 14:45 UTC, ChrisNLott commented on src/behaviors/Visibility/Visibility.js
> +    context: isBrowser ? window : {},
if we use null, should we also add null checks around https://github.com/ChrisNLott/Semantic-UI-React/blob/d3bd18cd7fca2be2ea5a32381b70798aa5de2c57/src/behaviors/Visibility/Visibility.js#L173?

2017-08-23 20:33 UTC, layershifter approved these changes

2017-08-24 07:22 UTC, lulalachen commented
Looking forward to this PR! Thanks

2017-08-26 02:19 UTC, tim-soft commented
I can't wait for this to merge, thank you!

2017-08-26 18:46 UTC, levithomason commented
Has this been tested in SSR?  I don't see how the `componentDidMount` would work when `context` is `null`:

```jsx
  componentDidMount() {
    const { context } = this.props
    context.addEventListener('scroll', this.handleScroll)
  }
```

In other components, we also exit methods early if they are accessing the `document` or `window`:

```jsx
  componentDidMount() {
    if (!isBrowser) return

    const { context } = this.props
    context.addEventListener('scroll', this.handleScroll)
  }
```

Would love to get some validation from SSR users before shipping.

2017-08-26 18:55 UTC, tim-soft commented
I can confirm that these changes fix my SSR apps, although I also need to make the same changes in `dist/commonjs/behaviors/Visibility/Visibility.js` and `dist/commonjs/modules/Sticky/Stick.js`

2017-08-26 20:25 UTC, ChrisNLott commented
@levithomason I tested it against my SSR app, but I will add null checks around the lifecycle methods too

2017-08-28 00:26 UTC, levithomason commented
@tim-soft and @ChrisNLott, thanks for investigating and reporting back.  Also, to @ChrisNLott for the updates.

Merging!  Will be released today :)

2017-08-28 00:26 UTC, merged

2017-08-28 00:51 UTC, levithomason commented
Released in `semantic-ui-react@0.72.0`