Fix for Portal usage of EventStack sub/unsub
Semantic-Org/Semantic-UI-React pull request #2099
Opened 2017-09-21 22:42 UTC by austinfox

Without this change, any event handlers added to EventStack under the 'Portal' namespace will be appended to an array. If another Portal is then mounted, new event handlers will be added to the EventStack and take precedence over the original portal's event handlers.

This change allows each portal to store its event handlers under its own namespace in EventStack, so when you click from one portal to another, the first one is appropriately closed.

2017-09-22 10:13 UTC, layershifter requested changes
@austinfox thanks for picking up this :+1: 

Proposed changes useless, because in fact it's equals to `default` pool of the `eventStack`. My initial proposal about the `exclusive` prop is also not ideal.

### Problem

We have a couple of bugs with multiple `Modal`s, `eventStack` solves them and improves performance.

What `eventStack` actually does? It has an entity called `pool`. Event handlers that included in `default` pool will be fired usual. But, only the last added event handler to the named pool will be fired when corresponding event will be occured.

You can open [this](https://react.semantic-ui.com/modules/modal#modal-example-multiple) `Modal` example. Open both modals and then press `Esc` key. Only top modal will be closed and it's correct. But, as we can see it causes problems for `Popup`s.

### Solution

So, my idea is to add the `eventPool` prop to the `Portal` which defaults to `default`:

```js
const { eventPool } = this.props

eventStack.sub('keydown', this.handleEscape, eventPool)
```

This prop should be also added to `Modal` and `Popup`, where it will be defaults to `Modal` and `default` accordingly. It will keep `Modal` working correctly and solve the problem with event propagation in `Popup`.

Let me know what you think.

2017-09-22 15:11 UTC, austinfox commented
@layershifter Yea I was thinking about adding a prop to Modal, Popup, and Portal. I'm not convinced it will be clear to others how to prevent this bug though even if we add eventPool as a prop. If they have an in-depth knowledge about the inner workings of Portal and eventStack, then yes they will be able to fix the problem. But by default, clicking on a popup and then clicking on another popup will be broken. Why not default to having each Popup use its own eventPool? I think that is standard behavior, whenever you click away from a popup is should almost always close.

2017-09-22 15:16 UTC, austinfox commented
@layershifter ignore my last comment. Taking a look at the EventStack code, I now understand what you mean. When the 'default' poolName is used, all handlers are called for that event. This will work just fine, I'll modify the PR in a few hours. Is there any way we can get this change into a new version of SUI react asap? My team site is currently breaking for IE users because we cannot use this feature. I had to rely on='focus' and do some other hacks that work well for chrome, Firefox, safari, and edge, but... sigh, IE...

2017-09-22 19:51 UTC, layershifter requested changes
Looks good to me. I left some comments about styling.

2017-09-22 19:51 UTC, layershifter commented on src/addons/Portal/Portal.js
> +    eventPool: PropTypes.string,
Please add prop in alphabetical order.

2017-09-22 19:51 UTC, layershifter commented on src/addons/Portal/Portal.js
> +    eventPool: 'default',
^

2017-09-22 19:51 UTC, layershifter commented on src/addons/Portal/Portal.js
> +      eventPool,
^

2017-09-22 19:51 UTC, layershifter commented on src/addons/Portal/Portal.js
> +    const { eventPool } = this.props
New line before this declaration is useless.

2017-09-22 19:56 UTC, layershifter commented
> When the 'default' poolName is used, all handlers are called for that event.

Exactly :+1: 

> Is there any way we can get this change into a new version of SUI react asap?

I will perform style changes tomorrow, if you will not do them before me :smile: I want to hear there @levithomason, too. I think that we can include it to next release on this weekend.

2017-09-22 20:02 UTC, layershifter approved these changes

2017-09-23 17:17 UTC, levithomason commented
I've been following this issue/PR and I'm happy with this result 👍.  Thanks for hashing it out guys.

2017-09-23 17:17 UTC, merged

2017-09-24 18:25 UTC, levithomason commented
Released in `semantic-ui-react@0.74.0`

2017-11-14 00:56 UTC, drewsbrew commented
Looking at the multiple modals example in the docs for v0.76, a single press of the Escape key closes both modals. I am seeing the same behavior in my project even with unique `eventPool` props values. Has this regressed or am I missing something?

2017-11-14 23:36 UTC, brianespinosa commented
@drewsbrew If that is what you are experiencing, please open up a separate bug report form with a codesandbox example.

2017-11-18 19:15 UTC, layershifter commented
@drewsbrew Bug actually exists, however @brianespinosa please create new issues instead of necroposting.

Will be fixed in #2329.