fix(Button): Add bool to propTypes of attached
Semantic-Org/Semantic-UI-React pull request #2105
Opened 2017-09-22 20:23 UTC by kasbah

fixes #2104

2017-09-22 20:26 UTC, levithomason commented
Looks like we may also need to update the ButtonGroup.

2017-09-22 20:38 UTC, kasbah commented
Looks to me like `Button.Group` doesn't attach properly in the middle currently. https://codepen.io/anon/pen/KXgrLd?editors=1111

2017-09-22 20:45 UTC, kasbah commented
Weirdly enough, any other string will work. :confused: https://codepen.io/anon/pen/KXgbpz?editors=1111

2017-09-22 21:40 UTC, kasbah commented
I pushed a commit that I think fixes the handling for `ButtonGroup`. Seems like [the CSS has no issues with middle attached groups](https://jsfiddle.net/u6kb1hfa/) so it should be fine, but I don't really know what I am doing, just copying and pasting things that seem to makes sense as I don't know how to do manual check if this behaves as desired yet.

2017-09-23 09:45 UTC, layershifter requested changes
@kasbah Thanks for PR, I've left some comments about styling. Also, `Button` should also use `useKeyOrValueAndKey` and use corresponding test.

2017-09-23 09:45 UTC, layershifter commented on src/elements/Button/ButtonGroup.js
> +  useKeyOrValueAndKey,
Please sort members in alphabetical order, i.e.:

```js
useKeyOnly,
useKeyOrValueAndKey,
useValueAndKey,
```

2017-09-23 09:45 UTC, layershifter commented on src/elements/Button/ButtonGroup.js
> +    useKeyOrValueAndKey(attached, 'attached'),
^, same there

2017-09-23 09:45 UTC, layershifter commented on test/specs/elements/Button/ButtonGroup-test.js
> +  common.propKeyOrValueAndKeyToClassName(ButtonGroup, 'attached', ['left', 'right', 'top', 'bottom'])
And there :smile:

2017-09-23 11:53 UTC, kasbah commented
Thanks @layershifter, I fixed the code style issues. `Button` is already using `useKeyOrValueAndKey`, that's where I copied it from. ;)

2017-09-23 12:05 UTC, layershifter commented
@kasbah Shame to me :rabbit: I've retriggered build, now it passed successfully. Great job :+1:

2017-09-23 12:06 UTC, layershifter approved these changes

2017-09-23 17:31 UTC, merged

2017-09-24 18:26 UTC, levithomason commented
Released in `semantic-ui-react@0.74.0`