Update webpack.config.js
Semantic-Org/Semantic-UI-React pull request #2171
Opened 2017-10-05 12:19 UTC by armendarabyan

fixing syntax error

2017-10-06 08:46 UTC, layershifter requested changes
@armendarabyan thanks :+1: Let's disable `comma-dangle` rule in `examples` directory:

### `.eslintrc`

```json
{
  "rules": {
    "comma-dangle": 0
  }
}
```

Webpack 2 examples should be also updated.

2017-10-08 09:48 UTC, layershifter approved these changes

2017-10-08 09:50 UTC, merged

2017-10-08 09:52 UTC, layershifter commented
Pushed some fixes, updated deps. I plan to deprecate these configs and made new examples with webpack 3 and CRA after we will merge #2131.

2017-10-16 07:38 UTC, levithomason commented
Released in `semantic-ui-react@0.75.0`