feat(DropdownMenu): Add direction support
Semantic-Org/Semantic-UI-React pull request #2174
Opened 2017-10-06 21:37 UTC by luisbd

This PR adds left directioning support to DropdownMenu.

Closes issue #1897

2017-10-14 14:25 UTC, layershifter commented on src/modules/Dropdown/Dropdown.js
> +    directionLeft: PropTypes.bool,
Please rename the prop to `direction` that will accept `left` as value.

2017-10-14 14:26 UTC, layershifter commented on src/modules/Dropdown/Dropdown.js
> +      useKeyOnly(directionLeft, 'left'),
Please sort it in alphabetical order, i.e.:

```js
useKeyOrValueAndKey(direction, 'direction'),
useKeyOrValueAndKey(pointing, 'pointing'),
```

2017-10-14 14:27 UTC, layershifter requested changes
@luisbd Thanks for PR :+1: I've left some comments about naming

2017-10-16 00:54 UTC, levithomason commented
This branch has a conflict that needs resolved.  Also, let's update docs with the new prop as well, there's `DropdownExampleMenuDirection` and `DropdownExampleMenuDirectionLeft`.  Not sure if we can do both, but let's see.

2017-10-17 19:49 UTC, closed without merging

2018-01-21 19:36 UTC, i7clock commented
What is the status here?

2018-02-14 22:43 UTC, levithomason commented
See https://github.com/Semantic-Org/Semantic-UI-React/issues/720, please refrain from status update requests.  It makes it difficult to keep up with notifications and responses to bugs/feature requests.

The best way to check on the status is to check the docs, issues, and PRs.  We have no work or status available outside of this.