Image: Inconsistent prop usage between Image and Icon for circular shape
Semantic-Org/Semantic-UI-React pull request #2225
Opened 2017-10-20 17:21 UTC by RetroCraft

Fixes #2217.

I'm on a very horrid laptop right now and can't run the test (webpack won't compile on this junk) but it should be fine.

2017-10-20 17:51 UTC, layershifter requested changes
@RetroCraft Please fix lint errors, `yarn run lint:fix`

```
  126:1  error    Trailing spaces not allowed                                                                                no-trailing-spaces
  138:1  error    Trailing spaces not allowed                                                                                no-trailing-spaces
  171:1  error    Trailing spaces not allowed                                                                                no-trailing-spaces
```

2017-10-20 18:57 UTC, layershifter commented
@RetroCraft Also this PR should be marked as **breaking** in title and initial comment. We also need to provide before/after usage example in the initial comment. See #2145 for example.

2017-10-20 19:31 UTC, RetroCraft commented
I think everything is good now.

2017-10-20 19:44 UTC, layershifter approved these changes

2017-10-22 15:28 UTC, merged

2017-11-05 00:01 UTC, levithomason commented
Released in `semantic-ui-react@0.76.0`