feat(Confirm): allow custom sizes
Semantic-Org/Semantic-UI-React pull request #2409
Opened 2018-01-05 21:32 UTC by ashurbeyli

fixes: #2405

2018-01-06 09:41 UTC, ashurbeyli commented
There are 2 failed tests that is not related to this issue.

![image](https://user-images.githubusercontent.com/8686481/34638544-3a743580-f2e7-11e7-9003-f408ff215346.png)

2018-01-06 19:04 UTC, layershifter requested changes
Thanks for PR, I've left some comments 👍

2018-01-06 19:04 UTC, layershifter commented on docs/app/Examples/addons/Confirm/Variations/ConfirmExampleSize.js
> +class ConfirmExampleSize extends Component {
Let's use a in definition export, i.e. `export default class ConfirmExampleSize`

2018-01-06 19:04 UTC, layershifter commented on docs/app/Examples/addons/Confirm/Variations/ConfirmExampleSize.js
> +  show = () => this.setState({ open: true })
Let's add more sense to handler's name: `show` => `handleButtonClick`

2018-01-06 19:04 UTC, layershifter commented on docs/app/Examples/addons/Confirm/Variations/ConfirmExampleSize.js
> +          onConfirm={this.handleConfirm}
Let's sort props in alphabetical order

2018-01-06 19:04 UTC, layershifter commented on src/addons/Confirm/Confirm.d.ts
> +  /** A modal can vary in size. */
Typo: _confirm_ can vary in size

2018-01-06 19:04 UTC, layershifter commented on src/addons/Confirm/Confirm.js
> +    size: PropTypes.oneOf(['fullscreen', 'large', 'mini', 'small', 'tiny']),
^

2018-01-06 19:04 UTC, layershifter commented on src/addons/Confirm/Confirm.js
> +    size: PropTypes.oneOf(['fullscreen', 'large', 'mini', 'small', 'tiny']),
Let's also add a `small` as value to `defaultProps`

2018-01-06 19:04 UTC, layershifter commented on test/specs/addons/Confirm/Confirm-test.js
> +  it('renders a large Modal', () => {
Let's update this test:

```jsx
describe('children', () => {
  it('renders a Modal', () => {
    shallow(<Confirm />)
       .type()
       .should.equal(Modal)
  })
})

describe('size', () => {
  it('has "small" size by default', () => {
    shallow(<Confirm />)
      .should.have.prop('size', 'small')
  })

  _.forEach(['fullscreen', 'large', 'mini', 'small', 'tiny'], size => {
    it(`applies "${size}" size', () => {
      shallow(<Confirm size={size} />)
        .should.have.prop('size', size)
    })
  })
})
```

2018-01-06 19:06 UTC, layershifter commented
@aabustamante yes, it's a known problem, rerun tests and everything should be fine. There are also lint issues:

![image](https://user-images.githubusercontent.com/14183168/34643001-6facf5aa-f325-11e7-9c8a-bd0f3d0cbe93.png)

Run `yarn run lint:fix` to fix them 👍

2018-01-07 01:31 UTC, aabustamante reviewed
Hi, @layershifter. I am a little bit confused. I think maybe my name was not the one you wanted to mention, anyway I added some comments.

2018-01-07 01:31 UTC, aabustamante commented on docs/app/Examples/addons/Confirm/Variations/ConfirmExampleSize.js
> +          size="large"
let's keep consistency with single quotes.

2018-01-07 01:31 UTC, aabustamante commented on docs/app/Examples/addons/Confirm/Variations/ConfirmExampleSize.js
> +          size="large"
Hi, @layershifter. I noticed that there is another file in this same path called `ConfirmExampleButtons`updated a year ago. This file I mention also mixes single quotes and double quotes, I remember that there are some lint tests for this, could this be indicating that these files are not in the coverage of the lint test? or maybe I'm wrong and there is no test for this, if that's the case I think we should create one, what do you think?.

2018-01-07 14:22 UTC, layershifter approved these changes

2018-01-10 04:43 UTC, levithomason commented on src/addons/Confirm/Confirm.js
> +    /** A modal can vary in size */
This should say `Confirm` and have a period:
```diff
-    /** A modal can vary in size */
+    /** A Confirm can vary in size. */
```

2018-01-10 04:45 UTC, levithomason commented
Although we can add this here, all extra Confirm props are passed to the underlying Modal automatically.  If we hoist one, we should technically hoist them all.  There is an issue for that in #1169.

Again, we can merge this one for now once comments are addressed.

2018-01-10 04:46 UTC, levithomason commented on src/addons/Confirm/Confirm.js
> +    /** A modal can vary in size */
Note, I tried to update this but it is on @ashurbeyli's `master` branch which I cannot push to.

2018-01-10 07:47 UTC, levithomason commented
Cool, was just about to make a release.  I'll wait for this to pass.

2018-01-10 07:52 UTC, merged

2018-01-10 07:52 UTC, levithomason commented
Thank you!

2018-01-10 08:19 UTC, levithomason commented
Released in `semantic-ui-react@0.77.2`