Babel preset env migration
Semantic-Org/Semantic-UI-React pull request #2594
Opened 2018-03-03 21:09 UTC by thetric

Use `babel-preset-env` instead of `babel-preset-es2015` as this is the recommended by the Babel dev team, see https://babeljs.io/env/.

2018-03-04 08:21 UTC, layershifter requested changes
We should define browser requirements for `preset-env`:

```
"targets": {
  "browsers": ["last 2 versions", "ie >= 11"]
}
```

2018-03-04 10:02 UTC, thetric commented
Suggestion for the browserlist: `last 2 versions, not ie < 11, not ie_mob <= 11`

2018-03-04 13:02 UTC, fracmak commented
Should throw in Firefox ESR

2018-03-04 13:37 UTC, thetric commented
Ok, so `last 2 versions, not ie < 11, not ie_mob <= 11, firefox esr, not op_mob < 37` should cover the most commonly used modern browsers. I additionally excluded older Opera Mobile versions (~2012).
Here a link to the [targeted browsers](http://browserl.ist/?q=last+2+versions%2C+not+ie+%3C+11%2C+not+ie_mob+%3C%3D+11%2C+firefox+esr%2C+not+op_mob+%3C+37)

2018-03-06 07:04 UTC, layershifter commented on package.json
> +  },
Let's keep the Babel's config in single place and move this to `preset-env.js`.

2018-03-06 11:10 UTC, thetric commented
@layershifter I've amended the last commit to move the env config to `build/preset-env.js`

2018-03-11 13:52 UTC, layershifter approved these changes
I've update the browsers list.

### Why?

1. We're making the component library there that should work in the most part of modern browsers, [updated config](http://browserl.ist/?q=chrome+%3E+24%2C+safari+%3E+8%2C+opera+%3E+15%2C+firefox+%3E+23%2C+not+ie+%3C+11%2C+not+ie_mob+%3C%3D+11%2C+last+8+versions) gives 97.48% coverage.
2. I choosed these versions because they [natively support](https://caniuse.com/#search=requestAni) `requestAnimationFrame()` that we use widely.

@thetric thanks again for your work there
@levithomason your opinion?

2018-03-11 15:46 UTC, thetric commented
IMO it doesn't make sense for Babel to target browsers that aren't supported by the semantic ui css, see https://github.com/Semantic-Org/Semantic-UI#browser-support

2018-03-11 16:00 UTC, thetric commented
BTW, I cleaned up the commit history of this Pr

2018-03-18 17:41 UTC, levithomason commented
>BTW, I cleaned up the commit history of this Pr

Heads up, we squash all PRs to one commit automatically 👍

2018-03-18 17:43 UTC, merged

2018-03-18 18:24 UTC, thetric commented
What about my comment about the configured browser target of `babel-preset-env`? With the current config we would target _more_ and _older_ browsers than Semantic UI (chrome 25-61, firefox 24-51, android < 4.4, ...). Why shouldn't we align with them?

2018-03-18 20:27 UTC, levithomason commented
I know of large enterprise consumers that rely on IE 11.  The standard here is coverage and consumers opposed to alignment with SUI.

2018-03-18 21:03 UTC, thetric commented
Did you see the effectively supported browsers in [browsersl.ist](http://browserl.ist/?q=chrome+%3E+24%2C+safari+%3E+8%2C+opera+%3E+15%2C+firefox+%3E+23%2C+not+ie+%3C+11%2C+not+ie_mob+%3C%3D+11%2C+last+8+versions)? The current babel config transpiles even for **IE 5.5** and other old browsers with non-existing global usage (Opera mobile 10-12, Android browser 2.3 - 4, Opera 16 - 48)

Oops, just noticed I accidentally dropped `modules: false`.

2018-03-18 21:08 UTC, levithomason commented
Got it.  Here's the [list of browsers](http://browserl.ist/?q=last+8+versions%2C+safari+%3E+8%2C+firefox+%3E+23%2C+chrome+%3E+24%2C+opera+%3E+15%2C+not+ie+%3C+11%2C+not+ie_mob+%3C%3D+11).  We're still leaving out 3.25% of browsers which seems a little large to me.

2018-03-19 15:34 UTC, brianespinosa commented
> Got it. Here's the list of browsers. We're still leaving out 3.25% of browsers which seems a little large to me.

@thetric based on the above list of browsers that @levithomason shared, that will not work for the enterprise project I currently maintain. I am sure there will be others with similar issues. We have to support (unfortunately) back to IE10.

2018-03-19 20:40 UTC, levithomason commented
Released in `semantic-ui-react@0.79.0`.

2018-03-19 20:41 UTC, levithomason commented
@brianespinosa if we screwed up support for you there, please open a PR restoring it.  We don't want to lose users, especially you!

2018-03-19 22:28 UTC, thetric commented
I compared the (unminified) build with the current browserslist and another build with my restricted one for more recent browsers and couldn't spot a difference - even when _explicitly including_ IE10. @brianespinosa So the current build should work fine even under IE10 :+1:

2018-03-19 23:04 UTC, brianespinosa commented
We have not updated to the latest version yet, partially because there's going to be a lot of work to update some custom styles for modals that we use that are going to significantly break from the upstream changes. So this is not breaking anything for us yet. I won't have any eyes on how this will function in IE10 for at least a few weeks.

@thetric if you've already tested this for IE10 then 👍

2018-03-19 23:13 UTC, thetric commented
Just compared the generated sources, not actually tested in a real browser

On Tue, 20 Mar 2018, 00:04 Brian Espinosa, <notifications@github.com> wrote:

> We have not updated to the latest version yet, partially because there's
> going to be a lot of work to update some custom styles for modals that we
> use that are going to significantly break from the upstream changes. So
> this is not breaking anything for us yet. I won't have any eyes on how this
> will function in IE10 for at least a few weeks.
>
> @thetric <https://github.com/thetric> if you've already tested this for
> IE10 then 👍
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/Semantic-Org/Semantic-UI-React/pull/2594#issuecomment-374415398>,
> or mute the thread
> <https://github.com/notifications/unsubscribe-auth/AS8R7hIzO3OHq2ZuIeMGA5V7kN9iOCD8ks5tgDmSgaJpZM4SbFQ9>
> .
>