Sticky: use SUI CSS classes
Semantic-Org/Semantic-UI-React pull request #2890
Opened 2018-06-07 15:00 UTC by pferreir

The `<Sticky />` component currently uses inline styles, which makes it difficult to take advantage of CSS to do some tricks like [this one](https://semantic-ui.com/modules/sticky.html#sticking-to-own-context).
This PR adds the standard Semantic UI classes meant for Sticky elements. Since it seems impossible to have the same element structure as with vanilla SUI, I'm adding `stuck-container`, `fixed-container` and `bound-container` classes that would allow for styling of the actual top-level container in its sticky state and "sub-states" (bound and fixed).

2018-06-07 20:47 UTC, layershifter commented
Marked as ready for review, I want to spend some time there in next few days.

2018-06-07 20:57 UTC, layershifter requested changes
Thanks for PR :+1: I've left some comments, but it's not all

2018-06-07 20:57 UTC, layershifter commented on src/modules/Sticky/Sticky.js
> +          style={this.computeStyle()}
Please order props in alphabetical order

2018-06-07 20:57 UTC, layershifter commented on src/modules/Sticky/Sticky.js
> +    const elementClasses = ['ui', 'sticky']
Let's use the `classnames` package there:
```jsx
const elementClasses = (
  'ui',
  bound ? 'bound bottom' : 'fixed',
  // etc
  'sticky',
)
```

2018-06-07 20:57 UTC, layershifter commented on src/modules/Sticky/Sticky.js
> +    const { sticky, bound, bottom } = this.state
Please order destructed props in alphabetical order

2018-06-07 20:57 UTC, layershifter commented on src/modules/Sticky/Sticky.js
> +      className,
The `className` prop is always last in `cx()` in our codebase

2018-06-07 20:57 UTC, layershifter commented on src/modules/Sticky/Sticky.js
>      this.setState({ bottom, top: null })
I'm not sure that we really need the `bound()` method, this case shows it because we have duplicate call of `setState()` there

2018-06-07 20:57 UTC, layershifter commented on src/modules/Sticky/Sticky.js
> +    }
This condition is strange, I think that we should just have `bottom: null` from the component's state there.

2018-06-18 08:58 UTC, layershifter approved these changes
Added some styling changes, @pferreir thank you for PR 👍

2018-06-18 23:58 UTC, merged

2018-06-26 01:38 UTC, levithomason commented
Released in `semantic-ui-react@0.81.2`.

2018-06-26 13:02 UTC, pferreir commented
Cheers! 👍