Dropdown: Dropdown.Header via shorthand prop
Semantic-Org/Semantic-UI-React pull request #501
Opened 2016-09-15 22:01 UTC by jcarbo

Adds support for a `header` shorthand prop for dropdown.

I was thinking of using a factory for `header` since it can have some other properties other than text (e.g. an icon). It would basically be:
```js
const createDropdownHeader = createFactory(DropdownHeader, value => ({ content: value }))
```

However, there's no precedent in the codebase for using a factory on a subcomponent so I was unsure where to put that. Some options would be:
1. `src/factories/index.js` (seems weird since the factory is not really usable globally.)
2. `src/modules/Dropdown/factories.js`
3. `src/modules/Dropdown/Dropdown.js` (just define it at the top of the file)

Kinda leaning option 3, but would love some other opinions.

2016-09-18 18:39 UTC, levithomason commented on src/modules/Dropdown/DropdownHeader.js
> +    PropTypes.element,
This can also accept a `PropTypes.object`.

2016-09-18 18:41 UTC, levithomason commented on src/modules/Dropdown/DropdownHeader.js
> +      {createIcon(icon)}
Let's also add `common.implementsIconProp()` to cover this usage.

2016-09-18 18:42 UTC, levithomason requested changes

2016-09-18 18:44 UTC, levithomason commented
>**Edit:** It seems the PR on standardizing childKey and shorthand props has some discussion related to this question about the factories. Perhaps we can hold off on the factory thing until and review this as-is until that's settled?

Agreed, the PR exploring this is #345 "Reusable Component Parts".  The idea is to create standard factories for all component parts and reuse them between all components.  We can wait for that work to resolve this issue.  What you have here is OK as is. 👍

2016-09-19 02:10 UTC, jcarbo commented
@levithomason - Addressed your comments and rebased against the most recent master. Should be g2g 👍

2016-09-19 16:43 UTC, levithomason approved these changes

2016-09-19 16:43 UTC, merged

2016-09-19 16:45 UTC, levithomason commented
Released in `stardust@0.44.5`, thanks much!