fix(Header): Fix `image` prop
Semantic-Org/Semantic-UI-React pull request #545
Opened 2016-09-24 16:13 UTC by layershifter

Fixes #542.

2016-09-24 16:14 UTC, layershifter commented on src/elements/Header/Header.js
> +  if ((image && typeof image !== 'boolean') || (icon && typeof icon !== 'boolean')) {
Impoved condition.

2016-09-24 16:14 UTC, layershifter commented on test/specs/elements/Header/Header-test.js
> +        .should.not.have.descendants('Image')
Added test.

2016-09-24 16:14 UTC, layershifter commented on test/specs/elements/Header/Header-test.js
> -        .should.not.have.className('icon')
Removed, it's covered by `common.implementsIconProp()`.

2016-09-24 16:15 UTC, layershifter commented on src/elements/Header/Header.js
> +    useKeyOnly(sub, 'sub'),
Sorted props.

2016-09-24 22:42 UTC, levithomason commented on test/specs/elements/Header/Header-test.js
> +    it('adds HeaderSubheader as child', () => {
This one should be covered by `implementsShorthandProp()` for `subheader`.  Should be able to remove it without a change in coverage.

2016-09-24 22:42 UTC, levithomason requested changes
Just one comment, then good to merge.

2016-09-25 09:23 UTC, layershifter commented on test/specs/elements/Header/Header-test.js
> +    it('adds HeaderSubheader as child', () => {
Looks like issue with merge, now okay.

2016-09-25 15:18 UTC, levithomason approved these changes

2016-09-25 15:18 UTC, merged

2016-09-25 15:20 UTC, levithomason commented
Released in `stardust@0.46.2`, thanks!