fix(Label): Add docs
Semantic-Org/Semantic-UI-React pull request #576
Opened 2016-10-01 09:34 UTC by layershifter

# WIP

This PR:
* adds all doc examples from [SUI](http://semantic-ui.com/elements/label.html);
* cleanups component and tests;
* improves props handling.

2016-10-01 10:42 UTC, layershifter commented
@levithomason @jcarbo I need review there

2016-10-01 19:59 UTC, levithomason requested changes
Looks great, left a few minor comments.

2016-10-01 19:59 UTC, levithomason commented on docs/app/Examples/elements/Label/Types/LabelExampleAttached.js
> +const imageStyles = {
Are these style required? I'd like to avoid any styles in the docs. It would seem that SUI alone should handle all styling.

2016-10-01 19:59 UTC, levithomason commented on docs/app/Examples/elements/Label/Types/LabelExampleRibbon.js
> +const imageStyles = {
Same regarding styles here, any way to remove them?

2016-10-01 19:59 UTC, levithomason commented on docs/app/Examples/elements/Label/Variations/LabelExampleCircular.js
> +  const colors = [
When we have data for examples, let's put it up top outside the scope of the example itself.

2016-10-01 19:59 UTC, levithomason commented on docs/app/Examples/elements/Label/Variations/LabelExampleSize.js
> +  const sizes = ['mini', 'tiny', 'small', 'medium', 'large', 'big', 'huge', 'massive']
More data here, let's move it up top. There are several other examples with data to update so I won't comment on all of them.

2016-10-01 20:29 UTC, layershifter commented on docs/app/Examples/elements/Label/Types/LabelExampleAttached.js
> +const imageStyles = {
If I remove them, example will look ugly 😿

2016-10-01 23:02 UTC, levithomason commented on docs/app/Examples/elements/Label/Types/LabelExampleAttached.js
> +const imageStyles = {
I don't think we should ever include styles in the examples.  I think it gives the impression that we require inline styles to be used for the example to work.  If we truly _must_ include styles, there are doc site css rules in the `index.ejs` template for this, but let's not put them in the JSX.

In this case, I think there is little enough difference that we can just leave them out:

![http://g.recordit.co/c0Js946Z9x.gif](http://g.recordit.co/c0Js946Z9x.gif)

Alternatively, we could use `<Segment padded>` to give whitespace similar to what the inline image styles did:

![http://g.recordit.co/EZpy8uQuZp.gif](http://g.recordit.co/EZpy8uQuZp.gif)

2016-10-02 02:56 UTC, jcarbo commented on docs/app/Examples/elements/Label/Variations/LabelExampleSize.js
> +  const sizes = ['mini', 'tiny', 'small', 'medium', 'large', 'big', 'huge', 'massive']
Actually, I think better would be to just use `Label._meta.props.size`, this way the sizes we give examples for are all the sizes the component supports. There are a few other places in the docs we should update to do this as well.

2016-10-02 02:57 UTC, jcarbo commented on docs/app/Examples/elements/Label/Variations/LabelExampleCircular.js
> +  const colors = [
Same comment re: sizes, should use `Label._meta.props.color`

2016-10-02 03:05 UTC, levithomason commented on docs/app/Examples/elements/Label/Variations/LabelExampleSize.js
> +  const sizes = ['mini', 'tiny', 'small', 'medium', 'large', 'big', 'huge', 'massive']
I don't want to expose the private _meta property. It may change or completely go away in the future.

2016-10-02 03:18 UTC, levithomason commented on docs/app/Examples/elements/Label/Variations/LabelExampleSize.js
> +  const sizes = ['mini', 'tiny', 'small', 'medium', 'large', 'big', 'huge', 'massive']
More info, meta used to have more keys and have more purpose. Over time, it keeps shrinking. Considering the parent, type, and name keys are only for documentation, I hope to pull them out of the code and into the doc block. We already parse the docblock for docs so grabbing type, parent, and name from there makes sense. 

This leaves only the props in the meta. In farther out, less defined goals, I'd like to better formalize how we define props to support the missing abilities of the component explorer #427.

2016-10-02 07:43 UTC, layershifter commented
Updated to `master` and fixed comments.

2016-10-03 04:31 UTC, levithomason approved these changes

2016-10-03 04:33 UTC, merged

2016-10-03 04:42 UTC, levithomason commented
Released in `stardust@0.51.1`