feat(Portal): Improve rendering
Semantic-Org/Semantic-UI-React pull request #666
Opened 2016-10-12 18:17 UTC by jcarbo

- Fixes bug in rendering composite react components as portal children
- Add closeOnBackgroundClick option to enable multiple portals on top of each other without closing all on click outside.
- Update modal to make use of this option.
- Fix portal wrapper having `undefined` as a class name if none was passed.

2016-10-13 04:47 UTC, jcarbo commented
@levithomason - this is ready for review 👍

2016-10-13 06:25 UTC, levithomason requested changes

2016-10-13 06:25 UTC, levithomason commented on src/addons/Portal/Portal.js
> +    closeOnBackgroundClick: customPropTypes.every([
If I'm reading corretly, the "Background" is the Dimmer when using a Modal with a Dimmer.  Though, this prop name wouldn't apply to say, a Popup, or some other component.  If so, what about using something like `closeOnRootNodeClick` instead?

2016-10-13 06:28 UTC, levithomason commented
A few other issues that did not have a diff to comment on:

1. The [Dimmer Variations](http://localhost:8080/modules/modal#dimmer-variations) example for `None` does not close on click outside.
1. The [Close Config](http://localhost:8080/modules/modal#close-config) example for `No Close On Click Outside` closes on click outside.  We should probably update this to show `closeOnBackgroundClick` with a Dimmer and `closeOnDocumentClick`with no Dimmer to illustrate the differences.
1. Could we also add a Multiple Modal example?

2016-10-13 15:30 UTC, jcarbo commented on src/addons/Portal/Portal.js
> +    this.portal = this.node.firstElementChild
```
LOG: 'children', Object{$$typeof: 60103, type: 'p', key: null, ref: null, props: Object{children: 'Hi'}, _owner: null, _store: Object{}}
LOG: 'firstElementChild', <p data-reactroot="">Hi</p>
      ✔ maintains ref to DOM node with host element
LOG: 'children', Object{$$typeof: 60103, type: function Component(props) { ... }, key: null, ref: null, props: Object{}, _owner: null, _store: Object{}}
LOG: 'firstElementChild', <p data-reactroot="">Hi</p>
      ✔ maintains ref to DOM node with React component
```

In both cases we need that actual DOM node, not a reference to the component or element.

2016-10-13 16:24 UTC, jcarbo commented
> The [Dimmer Variations](http://localhost:8080/modules/modal#dimmer-variations) example for `None` does not close on click outside.

This is expected behavior (works like SUI core). I added a notification popup on that button to explain what's happening. Essentially Modals can close on dimmer click. If there's no dimmer there's nothing to click on. You can manually specify `closeOnDocumentClick` which means any outside click.

> The [Close Config](http://localhost:8080/modules/modal#close-config) example for `No Close On Click Outside` closes on click outside.  We should probably update this to show `closeOnBackgroundClick` with a Dimmer and `closeOnDocumentClick`with no Dimmer to illustrate the differences.

Fixed

> Could we also add a Multiple Modal example?

Added

> Depending on the defaults we settle with, this could be a `BREAKING CHANGE: ...` PR.  If the Modal no longer behaves the same with `closeOnDocumentClick` (not closing on Dimmer click).

No defaults changed. Closing on dimmer click still works as expected. When dimmer is set to `false` that essentially means "no dimmer" and since Modals can close on dimmer click, if there's no dimmer there's nothing to click on.

2016-10-13 16:26 UTC, jcarbo commented
@levithomason - I think this should be g2g 👍 I also wound up renaming the modal examples to be inline with the new naming conventions.

2016-10-14 22:18 UTC, levithomason commented
Cool, we can merge this, but it doesn't actually fix #636 since Escape and a click on the Dimmer still closes all modals.  It should only close the top modal, then escape again would close the next modal. I'll update the description before merging.

2016-10-15 21:36 UTC, jcarbo commented
@levithomason - The example currently functions exactly like SUI core (see http://semantic-ui.com/modules/modal.html#/examples). Clicking the dimmer or pressing escape closes all open modals.

IMHO, this opens the possibility of multiple modals being open at once, and clicking outside closing only one. The example sets dimmer to false for the second modal, but if you left the default each modal would have its own dimmer so a click on the top modal's dimmer would only close that one. 

That being said, I'd be OK merging this but not closing #636. To truly handle that, I had an idea: Create a `Modal.Group` that would take an array of `Modal`s (either via prop or children) and show them in succession within the same Portal. We could implement the `allowMultiple` prop like SUI core:
- `allowMultiple: false` (default) would show each modal one at a time
- `allowMultiple: true` would stack each new modal on top of one another

This is basically just a stateful wrapper around multiple modals. Given the current `Modal` implementation, a user could create something like this themselves so I don't think it should be something we need to do for v1.

----

Sorry if that was a little scattered. The summary is that I think we should merge this since it fixes bugs (the `this.portal` bug is a blocker within in my company's app) and adds more functionality and complete any future work on separate PRs.

2016-10-17 13:45 UTC, jcarbo commented
Bump 😄

2016-10-17 18:08 UTC, levithomason commented
Thanks for the clarification, this makes sense.

2016-10-17 18:08 UTC, levithomason approved these changes

2016-10-17 18:08 UTC, merged

2016-10-17 18:26 UTC, levithomason commented
Released in `semantic-ui-react@0.56.2`