docs(Input): refactor, add trailing . in description, fix imports, fi…
Semantic-Org/Semantic-UI-React pull request #679
Opened 2016-10-14 03:24 UTC by dpkwhan

- refactor
- add trailing . in description
- fix imports
- fix wrong prop in Button
- add required prop 'selection' to Dropdown

2016-10-14 18:48 UTC, levithomason requested changes

2016-10-14 18:48 UTC, levithomason commented on docs/app/Examples/elements/Input/Variations/InputExampleActionDropdown.js
> +    action={<Dropdown selection basic floating options={options} defaultValue='page' />}
This should not be a`selection` Dropdown, reference: http://semantic-ui.com/elements/input#action

2016-10-14 18:48 UTC, levithomason commented on docs/app/Examples/elements/Input/Variations/InputExampleActionLabeledButton.js
> +    action={{ color: 'teal', label: 'right', icon: 'copy', content: 'Copy' }}
The prop `label` is for defining the label, the prop `labelPosition` is for placing it on the left/right.  This should be `labelPosition: 'right'`.

2016-10-14 18:48 UTC, levithomason commented on docs/app/Examples/elements/Input/Variations/InputExampleLeftActionLabeledButton.js
> +    action={{ color: 'teal', label: true, icon: 'cart', content: 'Checkout' }}
The previous `labeled` prop became `labelPosition`.  This should be `labelPosition: 'left'` which will place the `icon` as a label on the left.

2016-10-15 00:26 UTC, dpkwhan commented on docs/app/Examples/elements/Input/Variations/InputExampleActionLabeledButton.js
> +    action={{ color: 'teal', label: 'right', icon: 'copy', content: 'Copy' }}
Fixed.

2016-10-15 00:26 UTC, dpkwhan commented on docs/app/Examples/elements/Input/Variations/InputExampleLeftActionLabeledButton.js
> +    action={{ color: 'teal', label: true, icon: 'cart', content: 'Checkout' }}
Fixed.

2016-10-15 05:58 UTC, levithomason requested changes
One more update please, then I think we can merge it.

2016-10-15 05:58 UTC, levithomason commented on docs/app/Examples/elements/Input/Variations/InputExampleRightLabeled.js
> +    label={<Dropdown selection defaultValue='.com' options={options} />}
The `selection` prop should also not be added here:

### with `selection`
![image](https://cloud.githubusercontent.com/assets/5067638/19407800/80dc48d8-9261-11e6-9010-38b0e051b1a4.png)

### without `selection`

![image](https://cloud.githubusercontent.com/assets/5067638/19407797/693df0d2-9261-11e6-8649-8dfbfc944324.png)

2016-10-15 12:28 UTC, dpkwhan commented
@levithomason removed prop selection from Dropdown. Thank you for pointing this.

2016-10-17 17:28 UTC, merged

2016-10-17 17:28 UTC, levithomason commented
Thanks much :)