Add controlled modal example to docs
Semantic-Org/Semantic-UI-React pull request #769
Opened 2016-10-29 21:34 UTC by lewisblackwood

An example of a controlled modal component utilising the open prop. See issue https://github.com/Semantic-Org/Semantic-UI-React/issues/690.

@levithomason could you advise on how to include `open` in the prop table at the top of the document?

2016-10-29 21:54 UTC, levithomason commented
You can read about docs in the contributing guide:

https://github.com/Semantic-Org/Semantic-UI-React/blob/master/.github/CONTRIBUTING.md#documentation

2016-10-29 22:00 UTC, levithomason requested changes

2016-10-29 22:00 UTC, levithomason commented on docs/app/Examples/modules/Modal/Types/ModalExampleControlled.js
> +export default class ModalControlledExample extends Component {
Class name should match the file name.

2016-10-29 22:00 UTC, levithomason commented
Let me know if you have any other questions.

2016-10-31 12:10 UTC, lewisblackwood commented
I've added the reference for the `open` prop to `Modal.js` and `docgenInfo.json`, so the `open` prop is now included when the docs get built. 

It looks like this has broken some of the functionality of the Modal component, as the changes to the `open` prop don't get always get passed through to the Portal's state. For example, the controlled component I added now closes on a click outside the portal, but not when `handleClose` is called from the button.

@levithomason does the Modal component need a lifecycle method similar to that in the Dropdown component? Apologies if I've missed something simple here!

2016-10-31 18:40 UTC, levithomason commented
Previously the `open` prop was captured and spread in the `unhandled` variable.  This happens in the `render()` with the `getUnhandledProps()` util.

Now that the prop is being "handled" (added to the propTypes), you'll need to destructure it from props and pass it manually.  It is no longer captured in the `unhandled` variable.  Add it [here](https://github.com/Semantic-Org/Semantic-UI-React/pull/769/files#diff-e762b5cc3074c8997386b6de83cac7fbR177), the pass it to the Portal: `<Portal open={open} />`.

Clarification, `docgenInfo.json` is not committed to the repo.  It is auto generated from the propTypes, so just adding it to propTypes is enough.  Your changes to `docgenInfo.json` won't actually push to GitHub.  That file is also deleted and recreated on every build 👍 .

2016-11-03 14:33 UTC, lewisblackwood commented
Thanks for the clarification @levithomason!

The controlled component now works 👍 

What's the best way to maintain the functionality in the uncontrolled components, where `open` isn't passed as a prop?

I've been looking at the pattern of `activeIndex` in `Accordion`, but I'm not sure how to apply it to the modal. Should `Modal` now inherit from `AutoControlledComponent` and have `open` set as as `autoControlledProps`?

2016-11-03 15:28 UTC, jcarbo commented
@lewisblackwood - previously the modal was passing `open` through via `getUnhandledProps`. It's now passing it through explicitly, however the result is still the same. The `Portal` is the `AutoControlledComponent` so it will handle keeping track of `open` unless it receives a defined value for it. If `open` wasn't passed when using the Modal it will be passed as `undefined` to `Portal` which means that `Portal` will control the open state.

If the tests are all passing and the examples still work on this branch, you should be g2g. If not, maybe I'm misunderstanding how `AutoControlledComponent` works.

2016-11-03 16:40 UTC, lewisblackwood commented
Sorry @jcarbo, I should have been clearer above: I'm finding that the uncontrolled modal examples in the docs don't open on this branch (despite the passing tests). The controlled examples (mine and those under the 'Variations' header) are working.

2016-11-03 21:19 UTC, jcarbo commented
@lewisblackwood - indeed my understanding of AutoControlledComponent was wrong. I opened a PR with a potential fix and further discussion on how to handle this type of behavior: https://github.com/Semantic-Org/Semantic-UI-React/pull/788

2016-11-10 16:47 UTC, levithomason commented
@lewisblackwood there have been some updates to the Modal, you might want merge or rebase to the latest master to keep this PR up to speed.  It looks like there are some conflicts.

2016-11-11 13:10 UTC, lewisblackwood commented
@levithomason thanks for the heads-up; I've rebased this PR. Just waiting to see the outcome of https://github.com/Semantic-Org/Semantic-UI-React/pull/788 as this PR still breaks the uncontrolled modal right now.

2016-11-11 16:27 UTC, levithomason approved these changes

2016-11-16 07:19 UTC, levithomason commented
@lewisblackwood this PR should be unblocked and ready to update to the latest master. Give it a whirl and LMK how it goes.

Details in #788.

2016-11-16 15:19 UTC, lewisblackwood commented
@levithomason rad! All the modal examples are working now, this should be good to merge 👍

2016-11-16 15:38 UTC, levithomason commented
Fixed a typo in the prop description, will ship on pass. Thanks much 🎉

2016-11-16 15:44 UTC, merged