feat(Image): Render children appropriately
Semantic-Org/Semantic-UI-React pull request #784
Opened 2016-11-02 16:29 UTC by jcarbo

Previously you could render `<Image> with children but it'd be passed to the `<img>`, which is not technically valid markup.

Here's debug output from the `rendersChildren` test:
```js
<img className="ui image">
  Some content!
</img>
```

This updates the `Image` component to render the `.ui.image` wrapper if children are present, which brings this more inline with the `Input` component. Both are wrapping elements around an HTML element which technically can't take children. However, since there could be other elements inside the `.ui.image` wrapper this gives the user more control over how it renders.

2016-11-02 16:37 UTC, layershifter commented
@jcarbo May be we can add example in usage section that explains markup?

2016-11-02 17:07 UTC, jcarbo commented
Added an example for rendering children.
![screen shot 2016-11-02 at 1 05 34 pm](https://cloud.githubusercontent.com/assets/847027/19938907/12f9c7c8-a0fd-11e6-8f90-794915c656c0.png)

I also wound up:
- pulling in those wireframe images into this repo so we can serve them locally instead of hotlinking to SUI-core
- updating the title/descriptions of the Image examples to match SUI-core.

2016-11-02 21:53 UTC, levithomason requested changes
> pulling in those wireframe images into this repo so we can serve them locally instead of hotlinking to SUI-core

I have a suspicion that images are partly what is bloating the bundle / rebuild times, #765.  This PR brings the `docs` task build time up to ~56s for me with bundle/rebuild times to ~16s/3s :(  Compare this to previous bundle/rebuild times of ~7s/900ms.

This may be solvable with some build tweaking, but I'd rather not burden the most common use case (bundle, rebuild on change) for the less common use case (offline dev).

Lastly, we're also exposing unknown globals in the docs which I'd rather avoid.  I think it could confuse some users, but more so, I'd just rather keep the doc examples limited to "vanilla" React/SUIR code and not include any of our own proprietary code or internal conventions (ie `__BASE__`).

We can keep these for now, but I'm not sure there is a bright future for local images unless we solve these other things another way.  One idea is to match our file structure to SUI core docs structure, then just use `/` and rely on the `basename` to handle the rest.  Then, we can turn off any other image handling/processing that might be happening to help rebuild times.

2016-11-02 21:53 UTC, levithomason commented on docs/app/Examples/elements/Image/Variations/index.js
> -      </Message>
I think we should leave this warning in here.  I lost quite a bit time trying to debug why our images were oval and SUI core was circular.  Awkwardly enough, the `circular` class does _not_ make circular images, it makes "fully rounded" images if you will.  There is a similar warning in the SUI core docs.

2016-11-02 21:55 UTC, levithomason commented
Just one comment regarding the circular warning.

2016-11-04 05:01 UTC, jcarbo commented
@levithomason - I added the message about circular images back as requested. This should be g2g I think 👍

2016-11-04 09:14 UTC, layershifter commented
@jcarbo I aggre with @levithomason, `__BASE__` looks horrible. Do we really need it there?

I looked on Dropdown examples:
```js
image: { avatar: true, src: `${__BASE__}assets/images/avatar/small/jenny.jpg` },
```
It will be converted `/assets/images/avatar/small/jenny.jpg` in docs site and in local, too. I'm think can simply replace `${__BASE__}` with '/' there.

----

Also, looks there is missing main, test for children rendering.

2016-11-04 14:03 UTC, jcarbo commented
@layershifter - There was already a test for rendering children: https://github.com/Semantic-Org/Semantic-UI-React/blob/master/test/specs/elements/Image/Image-test.js#L13. It wasn't failing because it was just rendering children within the `<img>` tag:
```
<img className="ui image">
  Children are rendered here :|
</img>
```

I would've thought React would complain since that's not valid markup but maybe that's an issue withe `enzyme`?

I'll give a shot at removing `__BASE__`. FWIW, it was something introduced [before my time](https://github.com/Semantic-Org/Semantic-UI-React/pull/395/files#diff-1264673dc9aa9600177ee108da530f4eR71) so blame @levithomason 😆

2016-11-04 14:23 UTC, jcarbo commented
Just removed usage of `__BASE__`.

I realized what it was for - the docs for stardust were served from the `/stardust` path at `technologyadvice.github.io` while the local docs were served from the `/` path. `__BASE__` was used to account for the difference. After switching to SUI-react, both the prod and local docs are served from `/` so we can just use the root absolute path for images (e.g. `/assets/images/...`).

Also, I don't think the images are the culprit with slow build times:
- on first build: they may a little but it's just a raw copy/paste: https://github.com/Semantic-Org/Semantic-UI-React/blob/master/gulp/tasks/docs.js#L56-L59. I can't see how that would drastically decrease performance.
- for rebuilds: they will only be rebuilt if an image file was touched: https://github.com/Semantic-Org/Semantic-UI-React/blob/master/gulp/tasks/docs.js#L139-L148 so the images should have no effect on rebuild time.

I think this is g2g. @levithomason - when you're ready 👍

2016-11-04 16:01 UTC, layershifter commented on docs/app/Components/TAAttribution/TAAttribution.js
> +          src={'/assets/technologyadvice-logo-dark.png'}
`src={'/assets/technologyadvice-logo-dark.png'}` can be replaced with `src='/assets/technologyadvice-logo-dark.png'`

2016-11-04 16:03 UTC, layershifter commented on docs/app/Examples/elements/Image/States/ImageExampleHidden.js
> +const src = '/assets/images/wireframe/image.png'
Seems, we can move `src` to component:
```jsx
<Image hidden size='small' src='/assets/images/wireframe/image.png' />
```

2016-11-04 16:03 UTC, layershifter commented on docs/app/Examples/elements/Image/Types/ImageExampleImage.js
> +const src = '/assets/images/wireframe/image.png'
^

2016-11-04 16:04 UTC, layershifter commented on docs/app/Examples/elements/Image/Types/ImageExampleLink.js
> +const src = '/assets/images/wireframe/image-text.png'
```jsx
<Image
  as='a'
  href='http://google.com'
  target='_blank'
  size='medium'
  src='/assets/images/wireframe/image-text.png'
/>
```

Will look more clean.

2016-11-04 16:04 UTC, layershifter commented on docs/app/Examples/elements/Image/Types/ImageExampleWrapped.js
> +const src = '/assets/images/wireframe/image.png'
^

2016-11-04 16:04 UTC, layershifter commented on docs/app/Examples/elements/Image/Variations/ImageExampleAvatar.js
> +const src = '/assets/images/wireframe/square-image.png'
^

2016-11-04 19:52 UTC, jcarbo commented
@layershifter - just updated the `src` to put them inline. There were a few instances where the same `src` were used many times in the same example, so in those instances I kept it as a variable.

2016-11-05 18:52 UTC, levithomason commented
To be clear, we can/should use the globals (__BASE__, __DEV__, etc) in _private_ code such as doc site components themselves, I just don't want them to show up in example code snippets (docs/app/Examples/*).

2016-11-05 18:57 UTC, levithomason approved these changes

2016-11-05 19:04 UTC, merged