fix(Dimmer): Fix "simple" usage, add disabled prop
Semantic-Org/Semantic-UI-React pull request #795
Opened 2016-11-04 15:02 UTC by jcarbo

I realized that #782 breaks the "simple" example: http://react.semantic-ui.com/modules/dimmer#simple-dimmer. That should be enabled by virtue of having a parent with `ui dimmable dimmed`. See the SUI-core docs: http://semantic-ui.com/modules/dimmer.html#simple-dimmer

Digging into it further, two things stuck out to me:
- The reason the children were unclickable is because the dimmer always had the `visible` class, regardless of whether it was active. `active` controls the opacity, `visible` sets the `visibility`.
- `disabled` is a prop that overrides any active/visible state so we shouldn't be using it for that.

This fixes both issues.
- `visible` is only added when the dimmer is active, which removes the need to force `disabled`, which enables clicking on children and fixes the "simple" usage.
- We now expose `disabled` as a prop which conforms more to our API. A user can set that to override any active/visible state.

2016-11-05 17:21 UTC, levithomason requested changes
This is great, thanks much.  Couple updates to tests then we can merge this guy.

2016-11-05 17:21 UTC, levithomason commented on test/specs/modules/Dimmer/Dimmer-test.js
> +    it('adds the `transition visible` className when true', () => {
The common test can be configured to assert a className that is different than the prop name.  Should be able to replace this describe block with:

```jsx
common.propKeyOnlyToClassName(Dimmer, 'active', {
  className: 'active transition visible',
})
```

2016-11-05 17:21 UTC, levithomason commented on src/modules/Dimmer/Dimmer.js
> +      useKeyOnly(disabled, 'disabled'),
How about adding a common test for this?

```jsx
common.propKeyOnlyToClassName(Dimmer, 'disabled')
```

2016-11-06 01:22 UTC, jcarbo commented on src/modules/Dimmer/Dimmer.js
> +      useKeyOnly(disabled, 'disabled'),
Added 👍

2016-11-06 01:23 UTC, jcarbo commented
Added those tests and removed the ones for "active" that were testing duplicate functionality already covered by the common tests. Should be g2g 👍

2016-11-06 04:33 UTC, levithomason approved these changes

2016-11-06 04:33 UTC, merged