Feature/enforce handler args
Semantic-Org/Semantic-UI-React pull request #951
Opened 2016-11-28 16:45 UTC by jcarbo

Fixes #623

This updates the common tests for event handling to ensure any handlers that we wrap are called with `(event, data)` as arguments.

2016-11-28 21:21 UTC, jcarbo commented
@levithomason - thoughts on this approach? 

The alternative would be to have a separate common test like:
```js
common.passesPropsWithEvent(Component, 'onClick')
```

The issue there is that for non-built-in events (e.g. `onItemClick`) there's no way to reliably trigger the event.

Also I know we try to avoid big refactors, but assuming we go with this approach (updating the 'handles events' spec) I think it makes sense to just fix all of the handlers at once. These files currently have failing specs:
Looks like the following specs are failing that would need to be fixed:
- AccordionTitle
- BreadcrumbSection
- Checkbox
- Dropdown Component
- Form
- MenuItem
- Search Component
- SearchResult
- Select
- Step
- TableFooter
- TableHeaderCell

2016-11-29 05:31 UTC, levithomason commented
I like the idea of doing these all at once as it makes for less breaking changes and a clear upgrade path for users.

My idea for solving the handled/unhandled callbacks is precisely what you've done.  Though, I we can't assert the `data` param is `props` because sometimes it has other data like `state.value` in `TextArea` and `Input`.  There may be others that have arbitrary data as well.  Instead, we should match against an empty object `{}` for now.  Any further data specific logic I think should be the responsibility of individual component test.

2016-11-30 02:32 UTC, jcarbo commented
`calledWithMatch` is an alias for `calledWith(sinon.match(arg1), sinon.match(arg2))` and `sinon.match(object)` does an incomplete match on objects. So `calledWithMatch(event, props)` will pass as long as each key/value in `props` is in the second argument, even if there are additional key/value.

2016-11-30 03:38 UTC, jcarbo commented
@levithomason - ready for review 👍 

One question I had about `Dropdown`. Currently we pass `{ ...this.props, value: proposedValue }` as the second argument to `onChange` but only pass the props to the other handlers. Should we also pass the value to the rest of the event handlers? I was thinking something like:

```js
getHandlerProps = () => {
  return { ...this.props, value: this.state.value }
}

onChange = (e, value /* <- proposed value */) => {
  // ...
  props.onChange(e, { ...this.getHandlerProps(), value })
}

onClick = (e) => {
  // ...
  props.onClick(e, this.getHandlerProps())
}
```

2016-11-30 18:45 UTC, levithomason commented
>So calledWithMatch(event, props) will pass as long as the second arg is an object that includes each key/value in props, even if there are additional key/value.

This is correct, however, the test would have failed because the value in the `data` object is overridden as the event value and  `props.value != e.target.value`.  So, we can not be certain that all the props key/value pairs will appear in `data`.

>Should we also pass the value to the rest of the event handlers?

Initially, I don't think this is necessary in this case.  When the props change the ACC copies those values to state so the `props.value` will always equal `state.value`, except in the case of the `onChange` where we need to communicate the proposed new value.

That aside, it is a good idea IMO to have a SSOT for the handler props so I still like this idea.  It makes testing easier and the component stronger.

2016-11-30 19:30 UTC, layershifter commented
For clarity, `RatingIcon` is internal component and it can't be used outside `Rating` component. I think it's bad idea to export it.

2016-11-30 19:36 UTC, levithomason requested changes

2016-11-30 19:36 UTC, levithomason commented on src/modules/Search/Search.js
> +     * Called with the React Synthetic Event and current value on search input change.
Let's drop the signature info from the description here as well.

2016-11-30 19:36 UTC, levithomason commented on test/specs/modules/Accordion/AccordionTitle-test.js
> -  describe('onClick', () => {
Did we intend to drop these tests or update them?

2016-11-30 19:54 UTC, levithomason commented
### Doc Examples

I'm guessing there are several doc site examples that need to be updated to reflect the new changes as well.  Would finding handler prop names in the docs, `/on[A-Z]\w+=\{/`, and updating where necessary.

### RatingIcon

>For clarity, RatingIcon is internal component and it can't be used outside Rating component. I think it's bad idea to export it.

@layershifter Good call. We should make this a private component in this case.  Simply prefixing its name with `_` will make it private.  The common tests will then automatically assert that it _is not_ exposed anywhere in the API.

2016-11-30 19:56 UTC, levithomason commented on test/specs/commonTests.js
> +          expectedArgs = [eventShape, props]
I see all tests are passing, but how does this work for things like the Input onChange where the `data` arg's `value` key != to the `props` value key?  Same for Checkbox's `checked` prop.

2016-12-05 14:56 UTC, jcarbo commented on test/specs/modules/Accordion/AccordionTitle-test.js
> -  describe('onClick', () => {
Intentional given that all the functionality is being tested by the event-related tests within `isConformant`

2016-12-05 15:04 UTC, jcarbo commented on test/specs/commonTests.js
> +          expectedArgs = [eventShape, props]
`props` here isn't the Component's full props object, it's just:
```
const props = {
  ...requiredProps,
  [listenerName]: handlerSpy,
  'data-simulate-event-here': true,
}
```

So we're really just testing that arbitrary props get passed through (e.g. that `data-simulate-event-here` prop). Tests for additional data, like `checked` of a `Checkbox`, should be handled in that Component's test file.

2016-12-05 15:09 UTC, jcarbo commented
I started looking into making `RatingIcon` a private component and I don't really think we should:
- There are currently no other private components, the common tests for them don't actually work out of the box.
- While `RatingIcon` it's not usable outside of `Rating`, neither is `Dropdown.Divider` usable outside of `Dropdown`, nor `ItemImage` outside of `Item`.
- Our goal is to provide a Component API to give someone full control in rendering all SUI components, so we need to export it to allow full control over a `Rating`.

2016-12-05 17:14 UTC, levithomason approved these changes

2016-12-05 17:15 UTC, levithomason commented
That logic makes sense to me, thanks @jcarbo.

2016-12-05 17:16 UTC, merged

2016-12-07 01:26 UTC, levithomason commented
Released in `semantic-ui-react@0.62.0`.